In [1]:
import numpy as np
import pandas as pd

# Data Structures in Pandas

## Pandas makes use of two different data structures
    *Series
    *Data Frame
    
### Series represents data in a 1D form while data frames represent data in a 2D tabular form

In [ ]:
#pandas Series: one-dimensional array with labels

In [3]:
#obtain series from Python dictionaries (data structure for storing key-value pairs)
# keys of dictionaries act as index or label for values
dict={'a' : 3, 'b' : 'cat', 'c' : 2.5}
list1=[5,3,6]
pd.Series(list1) #

0    5
1    3
2    6
dtype: int64

In [4]:
oneD1 = pd.Series([100, 'cat', 310, 'gog', 500])
oneD1

0    100
1    cat
2    310
3    gog
4    500
dtype: object

In [5]:
oneD2 = pd.Series([100, 'cat', 310, 'gog', 500], ['Amy', 'Bobby', 'Cat', 'Don', 'Emma'])
oneD2

Amy      100
Bobby    cat
Cat      310
Don      gog
Emma     500
dtype: object

In [6]:
oneD3 = pd.Series([100, 'cat', 310, 'gog', 500], index=['Amy', 'Bobby', 'Cat', 'Don', 'Emma']) #the second list contains index
#index is the label of values
oneD3

Amy      100
Bobby    cat
Cat      310
Don      gog
Emma     500
dtype: object

In [7]:
oneD3.loc[['Cat','Emma']] #loc is a label-location based indexer for selection by labels- Cat and Donna

Cat     310
Emma    500
dtype: object

In [8]:
oneD3[[0,3,4]] #extract the data at index 0, 3 and 4

C:\Users\hp\AppData\Local\Temp\ipykernel_19904\694000842.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  oneD3[[0,3,4]] #extract the data at index 0, 3 and 4

Amy     100
Don     gog
Emma    500
dtype: object

In [9]:
oneD3.iloc[1] #.iloc is primarily integer position based (from 0 to length-1 of the axis). access index 1

'cat'

In [10]:
#check if there is a cat in the series index

'cat' in oneD3

False

In [11]:
'Cat' in oneD3

True

In [ ]:
#DataFrames- 2D data structure. Stores data in tabular form (rows and columns)
#<class 'pandas.core.frame.DataFrame'>

In [12]:
dict2={
     "name":['Narmin','Bahram','Anar'],
     'surname':['Abdullayeva', 'abdullayev', 'Behramov'],
     'age': [41,45,52]
}
df3=pd.DataFrame(dict2)
print(df3)

     name      surname  age
0  Narmin  Abdullayeva   41
1  Bahram   abdullayev   45
2    Anar     Behramov   52

In [13]:
d = {'A' : pd.Series([100., 200., 300.], index=['apple', 'pear', 'orange']),
     'B' : pd.Series([111., 222., 333., 4444.], index=['apple', 'pear', 'orange', 'melon'])}

In [ ]:
df = pd.DataFrame(d)
print(df) #when there are no values corresponding to an index then we have NaN

            A       B
apple   100.0   111.0
melon     NaN  4444.0
orange  300.0   333.0
pear    200.0   222.0

In [ ]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
df.index #list index values

Index([u'apple', u'melon', u'orange', u'pear'], dtype='object')

In [ ]:
df.columns #column names

Index([u'A', u'B'], dtype='object')

In [ ]:
pd.DataFrame(df, index=['orange', 'melon', 'apple'], columns=['A']) #specify which row/index and column we want to retain

            A
orange  300.0
melon     NaN
apple   100.0

### read in csv

In [2]:
import pandas as pd
import numpy as np

In [14]:
#Read in a very simple CSV file

file=r"D:\UNEC\python_data analytics\endangeredLang11.csv"
df1=pd.read_csv(file)
# print(df1.head(9))
print(df1.tail(10))

        ID                             Name in English  \
2712   283  Western Abenaki (United States of America)
2713  2093                                       Wichi
2714  1971                                     Yaeyama
2715  1365                                  Yazva Komi
2716   428                            Yiddish (Europe)
2717  1972                                    Yonaguni
2718  2018                                      Yucuna
2719  2015                           Yurutí (Colombia)
2720  2716                                   Zangskari
2721  2177                                     Zidgali

                                              Countries  \
2712                           United States of America
2713        Argentina, Bolivia (Plurinational State of)
2714                                              Japan
2715                                 Russian Federation
2716  Germany, Austria, Belarus, Belgium, Denmark, E...
2717                                              Japan
2718                                           Colombia
2719                                           Colombia
2720                                    India, Pakistan
2721                                               Oman

                                  Country codes alpha 3  \
2712                                                USA
2713                                           ARG, BOL
2714                                                JPN
2715                                                RUS
2716  DEU, AUT, BRB, BEL, DNK, EST, FIN, FRA, HUN, I...
2717                                                JPN
2718                                                COL
2719                                                COL
2720                                           IND, PAK
2721                                                OMN

     Degree_of_endangerment  Number of speakers  Latitude  Longitude  \
2712                Extinct                 NaN   43.0046   -72.2460
2713             Vulnerable                 NaN  -22.0041   -63.4130
2714    Severely endangered                 NaN   24.3420   124.1537
2715    Severely endangered                 NaN   60.0348    57.5360
2716  Definitely endangered                 NaN   53.3571    25.2465
2717    Severely endangered                 NaN   24.4580   122.9802
2718  Definitely endangered                 NaN   -1.2633   -70.6640
2719  Definitely endangered                 NaN    1.1370   -70.2136
2720  Definitely endangered                 NaN   34.0833    76.8500
2721  Critically endangered                 NaN   23.4027    58.0957

                            Description of the location
2712                                                NaN
2713                                                NaN
2714                      islands of the Yaeyama region
2715  the Yaz’va Valley in Krasnovishera County in n...
2716  earlier spoken in large areas mainly in Easter...
2717                                    Yonaguni Island
2718                                                NaN
2719                                                NaN
2720                                                NaN
2721                             Capital area of Muscat

### read in excel

In [119]:
import os

In [142]:
os.getcwd() #returns the current working directory.

'c:\\Users\\hp\\Desktop\\ders.prog\\python'

In [20]:
# file=r"D:\UNEC\python_data analytics\endangeredLang11.xlsx"

# Load spreadsheet
xl = pd.ExcelFile(r"D:\UNEC\python_data analytics\endangeredLang11.xlsx")
xl1=pd.read_excel(r"D:\UNEC\python_data analytics\endangeredLang11.xlsx")
# Print the sheet names
print(xl1.head(5))
# print(xl.sheet_names)

     ID Name in English                                          Countries  \
0  1022   South Italian                                              Italy
1  1023        Sicilian                                              Italy
2   383       Low Saxon  Germany, Denmark, Netherlands, Poland, Russian...
3   335      Belarusian  Belarus, Latvia, Lithuania, Poland, Russian Fe...
4   382         Lombard                                 Italy, Switzerland

          Country codes alpha 3 Degree of endangerment  Number of speakers  \
0                           ITA             Vulnerable           7500000.0
1                           ITA             Vulnerable           5000000.0
2       DEU, DNK, NLD, POL, RUS             Vulnerable           4800000.0
3  BRB, LVA, LTU, POL, RUS, UKR             Vulnerable           4000000.0
4                      ITA, CHE  Definitely endangered           3500000.0

   Latitude  Longitude                        Description of the location
0   40.9798    15.2490  Campania, Lucania (Basilicata), Abruzzi (Abruz...
1   37.4399    14.5019  Sicily (Sicilia), southern and central Calabri...
2   53.4029    10.3601  northern Germany, the north-eastern part of th...
3   53.9560    27.5756  Belarus except the Polesian-speaking south-wes...
4   45.7215     9.3273  the region of Lombardy (except the southernmos...

## Read in HTML data

In [21]:
import pandas as pd
import html5lib

### specify the html to be read in

In [22]:
uss=pd.read_html('https://simple.wikipedia.org/wiki/List_of_U.S._states')

In [23]:
print(type(uss)) # #this is a list of dataframes
print(uss)

<class 'list'>
[   Flag, name and postal abbreviation [1]  \
   Flag, name and postal abbreviation [1]
0                                 Alabama
1                                  Alaska
2                                 Arizona
3                                Arkansas
4                              California
5                                Colorado
6                             Connecticut
7                                Delaware
8                                 Florida
9                                 Georgia
10                                 Hawaii
11                                  Idaho
12                               Illinois
13                                Indiana
14                                   Iowa
15                                 Kansas
16                            Kentucky[B]
17                              Louisiana
18                                  Maine
19                               Maryland
20                       Massachusetts[B]
21                               Michigan
22                              Minnesota
23                            Mississippi
24                               Missouri
25                                Montana
26                               Nebraska
27                                 Nevada
28                          New Hampshire
29                             New Jersey
30                             New Mexico
31                               New York
32                         North Carolina
33                           North Dakota
34                                   Ohio
35                               Oklahoma
36                                 Oregon
37                        Pennsylvania[B]
38                           Rhode Island
39                         South Carolina
40                           South Dakota
41                              Tennessee
42                                  Texas
43                                   Utah
44                                Vermont
45                            Virginia[B]
46                             Washington
47                          West Virginia
48                              Wisconsin
49                                Wyoming

                                                     Cities  \
   Flag, name and postal abbreviation [1].1         Capital
0                                        AL      Montgomery
1                                        AK          Juneau
2                                        AZ         Phoenix
3                                        AR     Little Rock
4                                        CA      Sacramento
5                                        CO          Denver
6                                        CT        Hartford
7                                        DE           Dover
8                                        FL     Tallahassee
9                                        GA         Atlanta
10                                       HI        Honolulu
11                                       ID           Boise
12                                       IL     Springfield
13                                       IN    Indianapolis
14                                       IA      Des Moines
15                                       KS          Topeka
16                                       KY       Frankfort
17                                       LA     Baton Rouge
18                                       ME         Augusta
19                                       MD       Annapolis
20                                       MA          Boston
21                                       MI         Lansing
22                                       MN      Saint Paul
23                                       MS         Jackson
24                                       MO  Jefferson City
25                                       MT          Helena
26                                       NE         Lincoln
27                                       NV     Carson City
28                                       NH         Concord
29                                       NJ         Trenton
30                                       NM        Santa Fe
31                                       NY          Albany
32                                       NC         Raleigh
33                                       ND        Bismarck
34                                       OH        Columbus
35                                       OK   Oklahoma City
36                                       OR           Salem
37                                       PA      Harrisburg
38                                       RI      Providence
39                                       SC        Columbia
40                                       SD          Pierre
41                                       TN       Nashville
42                                       TX          Austin
43                                       UT  Salt Lake City
44                                       VT      Montpelier
45                                       VA        Richmond
46                                       WA         Olympia
47                                       WV      Charleston
48                                       WI         Madison
49                                       WY        Cheyenne

                              Established[A] Population [3] Total area[4]  \
   Largest (by population)[5] Established[A] Population [3]           mi2
0                  Huntsville   Dec 14, 1819        5024279         52420
1                   Anchorage    Jan 3, 1959         733391        665384
2                     Phoenix   Feb 14, 1912        7151502        113990
3                 Little Rock   Jun 15, 1836        3011524         53179
4                 Los Angeles    Sep 9, 1850       39538223        163695
5                      Denver    Aug 1, 1876        5773714        104094
6                  Bridgeport    Jan 9, 1788        3605944          5543
7                  Wilmington    Dec 7, 1787         989948          2489
8                Jacksonville    Mar 3, 1845       21538187         65758
9                     Atlanta    Jan 2, 1788       10711908         59425
10                   Honolulu   Aug 21, 1959        1455271         10932
11                      Boise    Jul 3, 1890        1839106         83569
12                    Chicago    Dec 3, 1818       12812508         57914
13               Indianapolis   Dec 11, 1816        6785528         36420
14                 Des Moines   Dec 28, 1846        3190369         56273
15                    Wichita   Jan 29, 1861        2937880         82278
16                 Louisville    Jun 1, 1792        4505836         40408
17                New Orleans   Apr 30, 1812        4657757         52378
18                   Portland   Mar 15, 1820        1362359         35380
19                  Baltimore   Apr 28, 1788        6177224         12406
20                     Boston    Feb 6, 1788        7029917         10554
21                    Detroit   Jan 26, 1837       10077331         96714
22                Minneapolis   May 11, 1858        5706494         86936
23                    Jackson   Dec 10, 1817        2961279         48432
24                Kansas City   Aug 10, 1821        6154913         69707
25                   Billings    Nov 8, 1889        1084225        147040
26                      Omaha    Mar 1, 1867        1961504         77348
27                  Las Vegas   Oct 31, 1864        3104614        110572
28                 Manchester   Jun 21, 1788        1377529          9349
29                     Newark   Dec 18, 1787        9288994          8723
30                Albuquerque    Jan 6, 1912        2117522        121590
31              New York City   Jul 26, 1788       20201249         54555
32                  Charlotte   Nov 21, 1789       10439388         53819
33                      Fargo    Nov 2, 1889         779094         70698
34                   Columbus    Mar 1, 1803       11799448         44826
35              Oklahoma City   Nov 16, 1907        3959353         69899
36                   Portland   Feb 14, 1859        4237256         98379
37               Philadelphia   Dec 12, 1787       13002700         46054
38                 Providence   May 29, 1790        1097379          1545
39                 Charleston   May 23, 1788        5118425         32020
40                Sioux Falls    Nov 2, 1889         886667         77116
41                  Nashville    Jun 1, 1796        6910840         42144
42                    Houston   Dec 29, 1845       29145505        268596
43             Salt Lake City    Jan 4, 1896        3271616         84897
44                 Burlington    Mar 4, 1791         643077          9616
45             Virginia Beach   Jun 25, 1788        8631393         42775
46                    Seattle   Nov 11, 1889        7705281         71298
47                 Charleston   Jun 20, 1863        1793716         24230
48                  Milwaukee   May 29, 1848        5893718         65496
49                   Cheyenne   Jul 10, 1890         576851         97813

            Land area[4]          Water area[4]         Number of Reps.
        km2          mi2      km2           mi2     km2 Number of Reps.
0    135767        50645   131171          1775    4597               7
1   1723337       570641  1477953         94743  245384               1
2    295234       113594   294207           396    1026               9
3    137732        52035   134771          1143    2961               4
4    423967       155779   403466          7916   20501              52
5    269601       103642   268431           452    1170               8
6     14357         4842    12542           701    1816               5
7      6446         1949     5047           540    1399               1
8    170312        53625   138887         12133   31424              28
9    153910        57513   148959          1912    4951              14
10    28313         6423    16635          4509   11678               2
11   216443        82643   214045           926    2398               2
12   149995        55519   143793          2395    6202              17
13    94326        35826    92789           593    1537               9
14   145746        55857   144669           416    1077               4
15   213100        81759   211754           520    1346               4
16   104656        39486   102269           921    2387               6
17   135659        43204   111898          9174   23761               6
18    91633        30843    79883          4537   11750               2
19    32131         9707    25142          2699    6990               8
20    27336         7800    20202          2754    7134               9
21   250487        56539   146435         40175  104052              13
22   225163        79627   206232          7309   18930               8
23   125438        46923   121531          1508    3907               4
24   180540        68742   178040           965    2501               8
25   380831       145546   376962          1494    3869               2
26   200330        76824   198974           524    1356               3
27   286380       109781   284332           791    2048               4
28    24214         8953    23187           397    1027               2
29    22591         7354    19047          1368    3544              12
30   314917       121298   314161           292     757               3
31   141297        47126   122057          7429   19240              26
32   139391        48618   125920          5201   13471              14
33   183108        69001   178711          1698    4397               1
34   116098        40861   105829          3965   10269              15
35   181037        68595   177660          1304    3377               5
36   254799        95988   248608          2391    6191               6
37   119280        44743   115883          1312    3397              17
38     4001         1034     2678           511    1324               2
39    82933        30061    77857          1960    5076               7
40   199729        75811   196350          1305    3379               1
41   109153        41235   106798           909    2355               9
42   695662       261232   676587          7365   19075              38
43   219882        82170   212818          2727    7064               4
44    24906         9217    23871           400    1035               1
45   110787        39490   102279          3285    8508              11
46   184661        66456   172119          4842   12542              10
47    62756        24038    62259           192     497               2
48   169635        54158   140268         11339   29367               8
49   253335        97093   251470           720    1864               1  ]

In [24]:
u = uss[0] #grab dataframe from index 0
print(type(u))

<class 'pandas.core.frame.DataFrame'>

### another url

In [25]:
url = 'http://www.fdic.gov/bank/individual/failed/banklist.html'

dfs = pd.read_html(url) #this is a list of dataframes

print(type(dfs))

<class 'list'>

In [26]:
df = dfs[0] #list of dataframes
print(df)

                               Bank Name               City          State  \
0     The First National Bank of Lindsay            Lindsay       Oklahoma
1  Republic First Bank dba Republic Bank       Philadelphia   Pennsylvania
2                          Citizens Bank           Sac City           Iowa
3               Heartland Tri-State Bank            Elkhart         Kansas
4                    First Republic Bank      San Francisco     California
5                         Signature Bank           New York       New York
6                    Silicon Valley Bank        Santa Clara     California
7                      Almena State Bank             Almena         Kansas
8             First City Bank of Florida  Fort Walton Beach        Florida
9                   The First State Bank      Barboursville  West Virginia

    Cert                 Aquiring Institution      Closing Date  \
0   4134   First Bank & Trust Co., Duncan, OK  October 18, 2024
1  27332    Fulton Bank, National Association    April 26, 2024
2   8758            Iowa Trust & Savings Bank  November 3, 2023
3  25851               Dream First Bank, N.A.     July 28, 2023
4  59017            JPMorgan Chase Bank, N.A.       May 1, 2023
5  57053                  Flagstar Bank, N.A.    March 12, 2023
6  24735  First Citizens Bank & Trust Company    March 10, 2023
7  15426                          Equity Bank  October 23, 2020
8  16748            United Fidelity Bank, fsb  October 16, 2020
9  14361                       MVB Bank, Inc.     April 3, 2020

   Fund  Sort ascending
0                 10547
1                 10546
2                 10545
3                 10544
4                 10543
5                 10540
6                 10539
7                 10538
8                 10537
9                 10536

In [27]:
whsSK=pd.read_html('https://en.wikipedia.org/wiki/List_of_World_Heritage_Sites_in_South_Korea')

In [3]:
import numpy as np
import pandas as pd

# Dealing with Missing Values (NAs)

In [143]:
#create sample data
df = pd.DataFrame([[1,np.nan,2],[2,3,5],[np.nan,4,6]]) #data has no values (NAs) in some cells
#we need to remove NA or NaN from the data frame

In [144]:
print(df)

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [145]:
## check if the data frames contains NA
print(df.isnull())

       0      1      2
0  False   True  False
1  False  False  False
2   True  False  False

In [146]:
## Drop NA values
## all rows with cells containing NA will be dropped
print(df.dropna(axis=0))

     0    1  2
1  2.0  3.0  5

In [127]:
## Drop columns where cells have NAs
print(df.dropna(axis=1))

   2
0  2
1  5
2  6

In [ ]:
print(df.dropna(axis=1,how="all"))

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [ ]:
## thresh parameter lets you specify a minimum number of non-null values for the row/column to be kept
print(df.dropna(thresh=2))

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

## Filling no values (NA) cells

In [ ]:
#fill NA entries with zero
print(df.fillna(0))

      0     1  2
0   1.0  13.0  2
1   2.0   3.0  5
2  13.0   4.0  6

In [ ]:
#specify a forward-fill to propagate the previous value forward
print(df.fillna(method="ffill"))

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  2.0  4.0  6

In [ ]:
#fill forward column wise
print(df.fillna(method="ffill",axis=1))

     0    1    2
0  1.0  1.0  2.0
1  2.0  3.0  5.0
2  NaN  4.0  6.0

In [ ]:
#back-fill to propagate the next values backward
print(df.fillna(method="bfill"))

     0    1  2
0  1.0  3.0  2
1  2.0  3.0  5
2  NaN  4.0  6

## Data Handling: Basics of Conditional Selection

In [39]:
# Load the data into a DataFrame
# data of endangered languages
data = pd.read_csv(r"D:\UNEC\python_data analytics\endangeredLang11.csv")
print(data.head(6))

     ID Name in English                                          Countries
0  1022   South Italian                                              Italy  \
1  1023        Sicilian                                              Italy
2   383       Low Saxon  Germany, Denmark, Netherlands, Poland, Russian...
3   335      Belarusian  Belarus, Latvia, Lithuania, Poland, Russian Fe...
4   382         Lombard                                 Italy, Switzerland
5   405          Romani  Albania, Germany, Austria, Belarus, Bosnia and...

                               Country codes alpha 3 Degree of endangerment
0                                                ITA             Vulnerable  \
1                                                ITA             Vulnerable
2                            DEU, DNK, NLD, POL, RUS             Vulnerable
3                       BRB, LVA, LTU, POL, RUS, UKR             Vulnerable
4                                           ITA, CHE  Definitely endangered
5  ALB, DEU, AUT, BRB, BIH, BGR, HRV, EST, FIN, F...  Definitely endangered

   Number of speakers  Latitude  Longitude
0           7500000.0   40.9798    15.2490  \
1           5000000.0   37.4399    14.5019
2           4800000.0   53.4029    10.3601
3           4000000.0   53.9560    27.5756
4           3500000.0   45.7215     9.3273
5           3500000.0   46.3165    22.3681

                         Description of the location
0  Campania, Lucania (Basilicata), Abruzzi (Abruz...
1  Sicily (Sicilia), southern and central Calabri...
2  northern Germany, the north-eastern part of th...
3  Belarus except the Polesian-speaking south-wes...
4  the region of Lombardy (except the southernmos...
5  many European countries, most densely in East-...

In [40]:
#isolate a column
data['Countries']

0                                                   Italy
1                                                   Italy
2       Germany, Denmark, Netherlands, Poland, Russian...
3       Belarus, Latvia, Lithuania, Poland, Russian Fe...
4                                      Italy, Switzerland
                              ...
2717                                                Japan
2718                                             Colombia
2719                                             Colombia
2720                                      India, Pakistan
2721                                                 Oman
Name: Countries, Length: 2722, dtype: object

In [155]:
#isolate 3 columns
df=data[['Countries','Name in English','Latitude']]
df

,Countries,Name in English,Latitude
0,Italy,South Italian,40.9798
1,Italy,Sicilian,37.4399
2,"Germany, Denmark, Netherlands, Poland, Russian...",Low Saxon,53.4029
3,"Belarus, Latvia, Lithuania, Poland, Russian Fe...",Belarusian,53.9560
4,"Italy, Switzerland",Lombard,45.7215
...,...,...,...
2717,Japan,Yonaguni,24.4580
2718,Colombia,Yucuna,-1.2633
2719,Colombia,Yurutí (Colombia),1.1370
2720,"India, Pakistan",Zangskari,34.0833
2721,Oman,Zidgali,23.4027

In [134]:
df.head(4)

                                           Countries Name in English  Latitude
0                                              Italy   South Italian   40.9798
1                                              Italy        Sicilian   37.4399
2  Germany, Denmark, Netherlands, Poland, Russian...       Low Saxon   53.4029
3  Belarus, Latvia, Lithuania, Poland, Russian Fe...      Belarusian   53.9560

In [43]:
#isolate rows
data['Countries'][3:9]

3    Belarus, Latvia, Lithuania, Poland, Russian Fe...
4                                   Italy, Switzerland
5    Albania, Germany, Austria, Belarus, Bosnia and...
6                                               Israel
7                                                India
8                        Germany, Belgium, Netherlands
Name: Countries, dtype: object

In [ ]:
# conditional selection

In [9]:
data[data['Number of speakers']<5000] #isolate the portion of df containing languages with less than 5000 speakers

,ID,Name in English,Countries,Country codes alpha 3,Degree of endangerment,Number of speakers,Latitude,Longitude,Description of the location
740,1125,Jirel,Nepal,NPL,Definitely endangered,4919.0,27.6419,86.2123,Dolakha district
741,468,Dolgan,Russian Federation,RUS,Definitely endangered,4865.0,71.3851,97.3388,Dudinka and Khatanga counties in former Taymyr...
742,2057,Romani (Colombia),Colombia,COL,Vulnerable,4858.0,NaN,NaN,Se ubican en los departamentos de Atlántico y ...
743,1160,Tsum,Nepal,NPL,Definitely endangered,4786.0,28.4723,85.0080,banks of Shar river
744,993,Northern Tlapanec,Mexico,MEX,Vulnerable,4771.0,17.4203,-98.7814,"Municipality of Zapotitlán Tablas, state of Gu..."
...,...,...,...,...,...,...,...,...,...
2534,131,|'Auni,South Africa,ZAF,Extinct,0.0,-26.0105,20.3630,NaN
2535,136,|Xam,South Africa,ZAF,Extinct,0.0,-32.2853,20.7590,NaN
2536,1443,ǁKu ǁ'e,South Africa,ZAF,Extinct,0.0,-29.9739,27.0812,Border area of Lesotho and South Africa
2537,1445,ǁKx'au,South Africa,ZAF,Extinct,0.0,-32.2896,21.7968,NaN
2538,130,ǁXegwi,South Africa,ZAF,Extinct,0.0,-25.3500,30.9900,"Lake Chrissie, Eastern Transvaal."

## Drop row/column

In [28]:
import numpy as np
import pandas as pd

In [29]:
# Load the data into a DataFrame
# data of endangered languages
data = pd.read_csv(r"D:\UNEC\python_data analytics\endangeredLang11.csv")
 
data.head(n=4)

,ID,Name in English,Countries,Country codes alpha 3,Degree_of_endangerment,Number of speakers,Latitude,Longitude,Description of the location
0,1022,South Italian,Italy,ITA,Vulnerable,7500000.0,40.9798,15.2490,"Campania, Lucania (Basilicata), Abruzzi (Abruz..."
1,1023,Sicilian,Italy,ITA,Vulnerable,5000000.0,37.4399,14.5019,"Sicily (Sicilia), southern and central Calabri..."
2,383,Low Saxon,"Germany, Denmark, Netherlands, Poland, Russian...","DEU, DNK, NLD, POL, RUS",Vulnerable,4800000.0,53.4029,10.3601,"northern Germany, the north-eastern part of th..."
3,335,Belarusian,"Belarus, Latvia, Lithuania, Poland, Russian Fe...","BRB, LVA, LTU, POL, RUS, UKR",Vulnerable,4000000.0,53.9560,27.5756,Belarus except the Polesian-speaking south-wes...

In [30]:
type(data)

pandas.core.frame.DataFrame

In [31]:
df=pd.DataFrame(data)
print(df)

        ID    Name in English  \
0     1022      South Italian
1     1023           Sicilian
2      383          Low Saxon
3      335         Belarusian
4      382            Lombard
...    ...                ...
2717  1972           Yonaguni
2718  2018             Yucuna
2719  2015  Yurutí (Colombia)
2720  2716          Zangskari
2721  2177            Zidgali

                                              Countries  \
0                                                 Italy
1                                                 Italy
2     Germany, Denmark, Netherlands, Poland, Russian...
3     Belarus, Latvia, Lithuania, Poland, Russian Fe...
4                                    Italy, Switzerland
...                                                 ...
2717                                              Japan
2718                                           Colombia
2719                                           Colombia
2720                                    India, Pakistan
2721                                               Oman

             Country codes alpha 3 Degree_of_endangerment  Number of speakers  \
0                              ITA             Vulnerable           7500000.0
1                              ITA             Vulnerable           5000000.0
2          DEU, DNK, NLD, POL, RUS             Vulnerable           4800000.0
3     BRB, LVA, LTU, POL, RUS, UKR             Vulnerable           4000000.0
4                         ITA, CHE  Definitely endangered           3500000.0
...                            ...                    ...                 ...
2717                           JPN    Severely endangered                 NaN
2718                           COL  Definitely endangered                 NaN
2719                           COL  Definitely endangered                 NaN
2720                      IND, PAK  Definitely endangered                 NaN
2721                           OMN  Critically endangered                 NaN

      Latitude  Longitude                        Description of the location
0      40.9798    15.2490  Campania, Lucania (Basilicata), Abruzzi (Abruz...
1      37.4399    14.5019  Sicily (Sicilia), southern and central Calabri...
2      53.4029    10.3601  northern Germany, the north-eastern part of th...
3      53.9560    27.5756  Belarus except the Polesian-speaking south-wes...
4      45.7215     9.3273  the region of Lombardy (except the southernmos...
...        ...        ...                                                ...
2717   24.4580   122.9802                                    Yonaguni Island
2718   -1.2633   -70.6640                                                NaN
2719    1.1370   -70.2136                                                NaN
2720   34.0833    76.8500                                                NaN
2721   23.4027    58.0957                             Capital area of Muscat

[2722 rows x 9 columns]

In [32]:
df.drop(df.index[0], inplace=True) #remove the first row, row at index 0
df

# data.drop(data.index[0], inplace=True) #remove the first row, row at index 0
# data

,ID,Name in English,Countries,Country codes alpha 3,Degree_of_endangerment,Number of speakers,Latitude,Longitude,Description of the location
1,1023,Sicilian,Italy,ITA,Vulnerable,5000000.0,37.4399,14.5019,"Sicily (Sicilia), southern and central Calabri..."
2,383,Low Saxon,"Germany, Denmark, Netherlands, Poland, Russian...","DEU, DNK, NLD, POL, RUS",Vulnerable,4800000.0,53.4029,10.3601,"northern Germany, the north-eastern part of th..."
3,335,Belarusian,"Belarus, Latvia, Lithuania, Poland, Russian Fe...","BRB, LVA, LTU, POL, RUS, UKR",Vulnerable,4000000.0,53.9560,27.5756,Belarus except the Polesian-speaking south-wes...
4,382,Lombard,"Italy, Switzerland","ITA, CHE",Definitely endangered,3500000.0,45.7215,9.3273,the region of Lombardy (except the southernmos...
5,405,Romani,"Albania, Germany, Austria, Belarus, Bosnia and...","ALB, DEU, AUT, BRB, BIH, BGR, HRV, EST, FIN, F...",Definitely endangered,3500000.0,46.3165,22.3681,"many European countries, most densely in East-..."
...,...,...,...,...,...,...,...,...,...
2717,1972,Yonaguni,Japan,JPN,Severely endangered,NaN,24.4580,122.9802,Yonaguni Island
2718,2018,Yucuna,Colombia,COL,Definitely endangered,NaN,-1.2633,-70.6640,NaN
2719,2015,Yurutí (Colombia),Colombia,COL,Definitely endangered,NaN,1.1370,-70.2136,NaN
2720,2716,Zangskari,"India, Pakistan","IND, PAK",Definitely endangered,NaN,34.0833,76.8500,NaN
2721,2177,Zidgali,Oman,OMN,Critically endangered,NaN,23.4027,58.0957,Capital area of Muscat

In [33]:
df.drop(df.index[2:7], inplace = True) #remove the first 2 rows, 
df #drop first 2 rows

,ID,Name in English,Countries,Country codes alpha 3,Degree_of_endangerment,Number of speakers,Latitude,Longitude,Description of the location
1,1023,Sicilian,Italy,ITA,Vulnerable,5000000.0,37.4399,14.5019,"Sicily (Sicilia), southern and central Calabri..."
2,383,Low Saxon,"Germany, Denmark, Netherlands, Poland, Russian...","DEU, DNK, NLD, POL, RUS",Vulnerable,4800000.0,53.4029,10.3601,"northern Germany, the north-eastern part of th..."
8,1020,Limburgian-Ripuarian,"Germany, Belgium, Netherlands","DEU, BEL, NLD",Vulnerable,2600000.0,50.7781,6.0864,Limburg provinces in Belgium and the Netherlan...
9,1943,Quechua of Southern Bolivia,Bolivia (Plurinational State of),BOL,Vulnerable,2300000.0,-18.0675,-65.7641,"Departments of Cochabamba, Chuquisaca, Potosí ..."
10,1565,Kumaoni,"India, Nepal","IND, NPL",Vulnerable,2003783.0,29.4778,79.8486,"Uttarakhand, also in Uttar Pradesh, Madhya Pra..."
...,...,...,...,...,...,...,...,...,...
2717,1972,Yonaguni,Japan,JPN,Severely endangered,NaN,24.4580,122.9802,Yonaguni Island
2718,2018,Yucuna,Colombia,COL,Definitely endangered,NaN,-1.2633,-70.6640,NaN
2719,2015,Yurutí (Colombia),Colombia,COL,Definitely endangered,NaN,1.1370,-70.2136,NaN
2720,2716,Zangskari,"India, Pakistan","IND, PAK",Definitely endangered,NaN,34.0833,76.8500,NaN
2721,2177,Zidgali,Oman,OMN,Critically endangered,NaN,23.4027,58.0957,Capital area of Muscat

In [34]:
df.drop(['Latitude'], axis = 1, inplace = True) #drop column called latitude

In [35]:
df.head(6)

,ID,Name in English,Countries,Country codes alpha 3,Degree_of_endangerment,Number of speakers,Longitude,Description of the location
1,1023,Sicilian,Italy,ITA,Vulnerable,5000000.0,14.5019,"Sicily (Sicilia), southern and central Calabri..."
2,383,Low Saxon,"Germany, Denmark, Netherlands, Poland, Russian...","DEU, DNK, NLD, POL, RUS",Vulnerable,4800000.0,10.3601,"northern Germany, the north-eastern part of th..."
8,1020,Limburgian-Ripuarian,"Germany, Belgium, Netherlands","DEU, BEL, NLD",Vulnerable,2600000.0,6.0864,Limburg provinces in Belgium and the Netherlan...
9,1943,Quechua of Southern Bolivia,Bolivia (Plurinational State of),BOL,Vulnerable,2300000.0,-65.7641,"Departments of Cochabamba, Chuquisaca, Potosí ..."
10,1565,Kumaoni,"India, Nepal","IND, NPL",Vulnerable,2003783.0,79.8486,"Uttarakhand, also in Uttar Pradesh, Madhya Pra..."
11,755,Aymara,"Bolivia (Plurinational State of), Chile, Peru","BOL, CHL, PER",Vulnerable,2000000.0,-68.3020,"Departamentos de Puno, Moquegua y Tacna, en ..."

In [40]:
data = {'name': ['Jason', 'Molly', 'Tina', 'Jake', 'Amy'],
        'year': [2012, 2012, 2013, 2014, 2014],
        'reports': [4, 24, 31, 2, 3]}
df = pd.DataFrame(data, index = ['Cochice', 'Pima', 'Santa Cruz', 'Maricopa', 'Yuma'])
df

             name  year  reports
Cochice     Jason  2012        4
Pima        Molly  2012       24
Santa Cruz   Tina  2013       31
Maricopa     Jake  2014        2
Yuma          Amy  2014        3

In [41]:
df.drop(['Cochice', 'Pima']) #By default axis=0, along the rows

            name  year  reports
Santa Cruz  Tina  2013       31
Maricopa    Jake  2014        2
Yuma         Amy  2014        3

## Subset & Index data

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Load the data into a DataFrame
# data of endangered languages
data = pd.read_csv(r"D:\UNEC\python_data analytics\endangeredLang11.csv")
 
data.head()

,ID,Name in English,Countries,Country codes alpha 3,Degree_of_endangerment,Number of speakers,Latitude,Longitude,Description of the location
0,1022,South Italian,Italy,ITA,Vulnerable,7500000.0,40.9798,15.2490,"Campania, Lucania (Basilicata), Abruzzi (Abruz..."
1,1023,Sicilian,Italy,ITA,Vulnerable,5000000.0,37.4399,14.5019,"Sicily (Sicilia), southern and central Calabri..."
2,383,Low Saxon,"Germany, Denmark, Netherlands, Poland, Russian...","DEU, DNK, NLD, POL, RUS",Vulnerable,4800000.0,53.4029,10.3601,"northern Germany, the north-eastern part of th..."
3,335,Belarusian,"Belarus, Latvia, Lithuania, Poland, Russian Fe...","BRB, LVA, LTU, POL, RUS, UKR",Vulnerable,4000000.0,53.9560,27.5756,Belarus except the Polesian-speaking south-wes...
4,382,Lombard,"Italy, Switzerland","ITA, CHE",Definitely endangered,3500000.0,45.7215,9.3273,the region of Lombardy (except the southernmos...

In [80]:
data[6:] #selecting all entries from index 6 onwards

,ID,Name in English,Countries,Country codes alpha 3,Degree of endangerment,Number of speakers,Latitude,Longitude,Description of the location
6,2211,Yiddish (Israel),Israel,ISR,Definitely endangered,3000000.0,32.0833,34.8333,"most speakers now live outside Europe, mainly ..."
7,1586,Gondi,India,IND,Vulnerable,2713790.0,19.5804,80.4418,"Madhya Pradesh (Betul, Chhindwara, Seoni, Mand..."
8,1020,Limburgian-Ripuarian,"Germany, Belgium, Netherlands","DEU, BEL, NLD",Vulnerable,2600000.0,50.7781,6.0864,Limburg provinces in Belgium and the Netherlan...
9,1943,Quechua of Southern Bolivia,Bolivia (Plurinational State of),BOL,Vulnerable,2300000.0,-18.0675,-65.7641,"Departments of Cochabamba, Chuquisaca, Potosí ..."
10,1565,Kumaoni,"India, Nepal","IND, NPL",Vulnerable,2003783.0,29.4778,79.8486,"Uttarakhand, also in Uttar Pradesh, Madhya Pra..."
...,...,...,...,...,...,...,...,...,...
2717,1972,Yonaguni,Japan,JPN,Severely endangered,NaN,24.4580,122.9802,Yonaguni Island
2718,2018,Yucuna,Colombia,COL,Definitely endangered,NaN,-1.2633,-70.6640,NaN
2719,2015,Yurutí (Colombia),Colombia,COL,Definitely endangered,NaN,1.1370,-70.2136,NaN
2720,2716,Zangskari,"India, Pakistan","IND, PAK",Definitely endangered,NaN,34.0833,76.8500,NaN
2721,2177,Zidgali,Oman,OMN,Critically endangered,NaN,23.4027,58.0957,Capital area of Muscat

In [73]:
data[::2] #select entries at even index locations
# data[:5][::2]

,ID,Name in English,Countries,Country codes alpha 3,Degree of endangerment,Number of speakers,Latitude,Longitude,Description of the location
0,1022,South Italian,Italy,ITA,Vulnerable,7500000.0,40.9798,15.2490,"Campania, Lucania (Basilicata), Abruzzi (Abruz..."
2,383,Low Saxon,"Germany, Denmark, Netherlands, Poland, Russian...","DEU, DNK, NLD, POL, RUS",Vulnerable,4800000.0,53.4029,10.3601,"northern Germany, the north-eastern part of th..."
4,382,Lombard,"Italy, Switzerland","ITA, CHE",Definitely endangered,3500000.0,45.7215,9.3273,the region of Lombardy (except the southernmos...
6,2211,Yiddish (Israel),Israel,ISR,Definitely endangered,3000000.0,32.0833,34.8333,"most speakers now live outside Europe, mainly ..."
8,1020,Limburgian-Ripuarian,"Germany, Belgium, Netherlands","DEU, BEL, NLD",Vulnerable,2600000.0,50.7781,6.0864,Limburg provinces in Belgium and the Netherlan...
...,...,...,...,...,...,...,...,...,...
2712,283,Western Abenaki (United States of America),United States of America,USA,Extinct,NaN,43.0046,-72.2460,NaN
2714,1971,Yaeyama,Japan,JPN,Severely endangered,NaN,24.3420,124.1537,islands of the Yaeyama region
2716,428,Yiddish (Europe),"Germany, Austria, Belarus, Belgium, Denmark, E...","DEU, AUT, BRB, BEL, DNK, EST, FIN, FRA, HUN, I...",Definitely endangered,NaN,53.3571,25.2465,earlier spoken in large areas mainly in Easter...
2718,2018,Yucuna,Colombia,COL,Definitely endangered,NaN,-1.2633,-70.6640,NaN
2720,2716,Zangskari,"India, Pakistan","IND, PAK",Definitely endangered,NaN,34.0833,76.8500,NaN

In [37]:
data.iloc[0:8,0:7] #specify the ranges of rows and columns
# data.iloc[0:8,0:7][::3]

#positional indexing
## iloc[row slicing, column slicing]

,ID,Name in English,Countries,Country codes alpha 3,Degree of endangerment,Number of speakers,Latitude
0,1022,South Italian,Italy,ITA,Vulnerable,7500000.0,40.9798
3,335,Belarusian,"Belarus, Latvia, Lithuania, Poland, Russian Fe...","BRB, LVA, LTU, POL, RUS, UKR",Vulnerable,4000000.0,53.9560
6,2211,Yiddish (Israel),Israel,ISR,Definitely endangered,3000000.0,32.0833

In [76]:
# select all columns for rows of index values 0 and 10
data.loc[[0, 10], :]
# data.loc[0:10, :]

,ID,Name in English,Countries,Country codes alpha 3,Degree of endangerment,Number of speakers,Latitude,Longitude,Description of the location
0,1022,South Italian,Italy,ITA,Vulnerable,7500000.0,40.9798,15.2490,"Campania, Lucania (Basilicata), Abruzzi (Abruz..."
10,1565,Kumaoni,"India, Nepal","IND, NPL",Vulnerable,2003783.0,29.4778,79.8486,"Uttarakhand, also in Uttar Pradesh, Madhya Pra..."

In [ ]:
#isolate rows and columns
data[['Countries','Name in English']][4:8]
# data[4:8][['Countries','Name in English']] we will get the same result

                                           Countries   Name in English
4                                 Italy, Switzerland           Lombard
5  Albania, Germany, Austria, Belarus, Bosnia and...            Romani
6                                             Israel  Yiddish (Israel)
7                                              India             Gondi

In [3]:

data[data.Countries == "Italy"] #isolate by row names
# data[(data.Countries == "Italy") & (data.ID >= 2000)]

,ID,Name in English,Countries,Country codes alpha 3,Degree_of_endangerment,Number of speakers,Latitude,Longitude,Description of the location
0,1022,South Italian,Italy,ITA,Vulnerable,7500000.0,40.9798,15.2490,"Campania, Lucania (Basilicata), Abruzzi (Abruz..."
1,1023,Sicilian,Italy,ITA,Vulnerable,5000000.0,37.4399,14.5019,"Sicily (Sicilia), southern and central Calabri..."
13,399,Piedmontese,Italy,ITA,Definitely endangered,2000000.0,45.2013,7.8662,"Piedmont Region except the Novara Province, th..."
36,337,Campidanese,Italy,ITA,Definitely endangered,900000.0,39.2991,8.9868,southern Sardinia
53,353,Friulian,Italy,ITA,Definitely endangered,600000.0,46.1037,13.1396,the Autonomous Region Friuli-Venezia Giulia ex...
80,381,Logudorese,Italy,ITA,Definitely endangered,400000.0,40.1116,9.1845,central Sardinia
157,408,Sassarese,Italy,ITA,Definitely endangered,120000.0,40.6139,8.6132,northwestern Sardinia; an outlying dialect of ...
170,356,Gallurese,Italy,ITA,Definitely endangered,100000.0,40.8802,9.4482,northeastern Sardinia; an outlying dialect of ...
197,1347,Arbëresh,Italy,ITA,Definitely endangered,80000.0,40.9321,14.8645,"(i) Adriatic zone: Montecilfone, Campomarino, ..."
212,1330,Gallo-Sicilian,Italy,ITA,Definitely endangered,65000.0,38.0167,14.5994,"Nicosia, Sperlinga, Piazza Armerina, Valguarne..."
320,565,Ladin,Italy,ITA,Definitely endangered,30000.0,46.5531,11.8597,"several towns and villages in the Dolomites, i..."
391,1614,Griko (Salento),Italy,ITA,Severely endangered,20000.0,40.1578,18.2208,the Salento peninsula in Lecce Province in sou...
510,1343,Algherese Catalan,Italy,ITA,Definitely endangered,10000.0,40.5638,8.3276,the town of Alghero in northwestern Sardinia; ...
729,1349,Molise Croatian,Italy,ITA,Severely endangered,5000.0,41.8787,14.7065,"the villages of Montemitro (Mundimitar), San F..."
964,1339,Griko (Calabria),Italy,ITA,Severely endangered,2000.0,37.9961,15.9329,a few villages near Reggio di Calabria in sout...
1198,1511,Mòcheno,Italy,ITA,Definitely endangered,1000.0,46.1194,11.3258,"Palù (Palai), Fierozzo (Florutz) and Frassilon..."
1205,1348,Resian,Italy,ITA,Definitely endangered,1000.0,46.3734,13.3058,Resia in the northeastern part of Udine Provin...
1315,351,Faetar,Italy,ITA,Definitely endangered,600.0,41.3265,15.1721,Faeto and Celle San Vito in Foggia Province in...
1455,1345,Cimbrian,Italy,ITA,Definitely endangered,400.0,45.8670,11.4268,vigorously spoken in Luserna (Lusern) in Trent...
1506,357,Gardiol,Italy,ITA,Severely endangered,340.0,39.4658,15.9933,Guardia Piedmontese in Calabria; an outlying d...
1663,1344,Töitschu,Italy,ITA,Severely endangered,200.0,45.6913,7.8682,the village of Issime (Eischeme) in the upper ...

In [4]:
x=data.loc[data['Countries'].isin(['Italy','Germany'])] #isolate by two row labels

In [5]:
x.head(20)

,ID,Name in English,Countries,Country codes alpha 3,Degree_of_endangerment,Number of speakers,Latitude,Longitude,Description of the location
0,1022,South Italian,Italy,ITA,Vulnerable,7500000.0,40.9798,15.2490,"Campania, Lucania (Basilicata), Abruzzi (Abruz..."
1,1023,Sicilian,Italy,ITA,Vulnerable,5000000.0,37.4399,14.5019,"Sicily (Sicilia), southern and central Calabri..."
13,399,Piedmontese,Italy,ITA,Definitely endangered,2000000.0,45.2013,7.8662,"Piedmont Region except the Novara Province, th..."
36,337,Campidanese,Italy,ITA,Definitely endangered,900000.0,39.2991,8.9868,southern Sardinia
53,353,Friulian,Italy,ITA,Definitely endangered,600000.0,46.1037,13.1396,the Autonomous Region Friuli-Venezia Giulia ex...
80,381,Logudorese,Italy,ITA,Definitely endangered,400000.0,40.1116,9.1845,central Sardinia
157,408,Sassarese,Italy,ITA,Definitely endangered,120000.0,40.6139,8.6132,northwestern Sardinia; an outlying dialect of ...
170,356,Gallurese,Italy,ITA,Definitely endangered,100000.0,40.8802,9.4482,northeastern Sardinia; an outlying dialect of ...
197,1347,Arbëresh,Italy,ITA,Definitely endangered,80000.0,40.9321,14.8645,"(i) Adriatic zone: Montecilfone, Campomarino, ..."
212,1330,Gallo-Sicilian,Italy,ITA,Definitely endangered,65000.0,38.0167,14.5994,"Nicosia, Sperlinga, Piazza Armerina, Valguarne..."
320,565,Ladin,Italy,ITA,Definitely endangered,30000.0,46.5531,11.8597,"several towns and villages in the Dolomites, i..."
391,1614,Griko (Salento),Italy,ITA,Severely endangered,20000.0,40.1578,18.2208,the Salento peninsula in Lecce Province in sou...
406,384,Sorbian,Germany,DEU,Definitely endangered,19500.0,51.5001,14.4744,Lusatia (Lausitz [Łužica or Łužyca]) region ar...
510,1343,Algherese Catalan,Italy,ITA,Definitely endangered,10000.0,40.5638,8.3276,the town of Alghero in northwestern Sardinia; ...
534,394,North Frisian,Germany,DEU,Severely endangered,10000.0,54.7341,8.7478,western coast of Schleswig north of Husum incl...
729,1349,Molise Croatian,Italy,ITA,Severely endangered,5000.0,41.8787,14.7065,"the villages of Montemitro (Mundimitar), San F..."
964,1339,Griko (Calabria),Italy,ITA,Severely endangered,2000.0,37.9961,15.9329,a few villages near Reggio di Calabria in sout...
1198,1511,Mòcheno,Italy,ITA,Definitely endangered,1000.0,46.1194,11.3258,"Palù (Palai), Fierozzo (Florutz) and Frassilon..."
1205,1348,Resian,Italy,ITA,Definitely endangered,1000.0,46.3734,13.3058,Resia in the northeastern part of Udine Provin...
1208,346,Saterlandic,Germany,DEU,Severely endangered,1000.0,53.1059,7.6787,"Strücklingen (Strukelje), Ramsloh (Romelse) an..."

In [8]:
data[(data.Countries == "India") & (data.Degree_of_endangerment=="Vulnerable")]

,ID,Name in English,Countries,Country codes alpha 3,Degree_of_endangerment,Number of speakers,Latitude,Longitude,Description of the location
7,1586,Gondi,India,IND,Vulnerable,2713790.0,19.5804,80.4418,"Madhya Pradesh (Betul, Chhindwara, Seoni, Mand..."
16,1591,Kurux (India),India,IND,Vulnerable,1751489.0,22.1467,85.2758,Jharkhand and Bihar
18,1585,Tulu,India,IND,Vulnerable,1722768.0,12.0178,75.7067,"Karnataka, Andhra Pradesh, Kerala"
26,1227,Meithei,India,IND,Vulnerable,1250000.0,24.7667,93.8946,"Manipur (throughout, but concentrated in the M..."
33,1577,Kui,India,IND,Vulnerable,916222.0,19.5908,83.9575,"Orissa (Phulbani, Koraput, Ganjam); also in An..."
...,...,...,...,...,...,...,...,...,...
417,1142,Pochuri,India,IND,Vulnerable,17000.0,25.6712,94.7790,"Nagaland, Phek Dt."
467,1168,Khampti,India,IND,Vulnerable,13000.0,27.8827,96.5093,"Lohit Valley Dt., concentrated in and around C..."
594,1182,Rongpo,India,IND,Vulnerable,8000.0,30.7229,79.7387,"Uttarakhand, Chamoli dt."
867,1096,Sherdukpen,India,IND,Vulnerable,3000.0,27.1935,92.3510,NaN
2653,1566,Padri,India,IND,Vulnerable,NaN,33.8886,76.3000,Jammu and Kashmir

In [9]:
df=data[:] #make a copy of the data frame stored in data

In [10]:
df.rename(columns={'Number of speakers':'Number'}, inplace=True) #replace "Number of Speakers" with "Number"

In [116]:
df.head(5)

,ID,Name in English,Countries,Country codes alpha 3,Degree of endangerment,Number,Latitude,Longitude,Description of the location
0,1022,South Italian,Italy,ITA,Vulnerable,7500000.0,40.9798,15.2490,"Campania, Lucania (Basilicata), Abruzzi (Abruz..."
1,1023,Sicilian,Italy,ITA,Vulnerable,5000000.0,37.4399,14.5019,"Sicily (Sicilia), southern and central Calabri..."
2,383,Low Saxon,"Germany, Denmark, Netherlands, Poland, Russian...","DEU, DNK, NLD, POL, RUS",Vulnerable,4800000.0,53.4029,10.3601,"northern Germany, the north-eastern part of th..."
3,335,Belarusian,"Belarus, Latvia, Lithuania, Poland, Russian Fe...","BRB, LVA, LTU, POL, RUS, UKR",Vulnerable,4000000.0,53.9560,27.5756,Belarus except the Polesian-speaking south-wes...
4,382,Lombard,"Italy, Switzerland","ITA, CHE",Definitely endangered,3500000.0,45.7215,9.3273,the region of Lombardy (except the southernmos...

In [117]:
df[(df.Countries == "India") & (df.Number<100)] #specify 2 conditions to be fulfilled

,ID,Name in English,Countries,Country codes alpha 3,Degree of endangerment,Number,Latitude,Longitude,Description of the location
1912,2455,Onge,India,IND,Critically endangered,50.0,10.6390,92.4938,NaN
1922,1363,Sentilese,India,IND,Critically endangered,50.0,11.5446,92.2576,"Andaman Islands, North Sentinel Island"
1957,1364,Jarawa,India,IND,Critically endangered,31.0,12.6028,92.7520,South Andaman Island
2172,2722,Great andamanese,India,IND,Critically endangered,5.0,12.2326,92.9031,Middle and North Adaman
2284,429,Ahom,India,IND,Extinct,0.0,26.5393,92.5378,NaN
2291,513,Andro,India,IND,Extinct,0.0,24.8415,94.0539,NaN
2323,519,Chairel,India,IND,Extinct,0.0,24.9760,94.2407,NaN
2477,443,Rangkas,India,IND,Extinct,0.0,30.0358,80.1342,NaN
2481,558,Sengmai,India,IND,Extinct,0.0,24.6445,94.0567,NaN

## Basic Data Grouping

In [3]:
import pandas as pd
import numpy as np

In [4]:
# Load the data into a DataFrame
data = pd.read_csv(r"D:\UNEC\python_data analytics\endangeredLang11.csv")
 
data.head(n=6)

,ID,Name in English,Countries,Country codes alpha 3,Degree_of_endangerment,Number of speakers,Latitude,Longitude,Description of the location
0,1022,South Italian,Italy,ITA,Vulnerable,7500000.0,40.9798,15.2490,"Campania, Lucania (Basilicata), Abruzzi (Abruz..."
1,1023,Sicilian,Italy,ITA,Vulnerable,5000000.0,37.4399,14.5019,"Sicily (Sicilia), southern and central Calabri..."
2,383,Low Saxon,"Germany, Denmark, Netherlands, Poland, Russian...","DEU, DNK, NLD, POL, RUS",Vulnerable,4800000.0,53.4029,10.3601,"northern Germany, the north-eastern part of th..."
3,335,Belarusian,"Belarus, Latvia, Lithuania, Poland, Russian Fe...","BRB, LVA, LTU, POL, RUS, UKR",Vulnerable,4000000.0,53.9560,27.5756,Belarus except the Polesian-speaking south-wes...
4,382,Lombard,"Italy, Switzerland","ITA, CHE",Definitely endangered,3500000.0,45.7215,9.3273,the region of Lombardy (except the southernmos...
5,405,Romani,"Albania, Germany, Austria, Belarus, Bosnia and...","ALB, DEU, AUT, BRB, BIH, BGR, HRV, EST, FIN, F...",Definitely endangered,3500000.0,46.3165,22.3681,"many European countries, most densely in East-..."

In [4]:
large=data.sort_values(by='Number of speakers', ascending=False)#sort in descending order
# large1=data.sort_values(by='ID', ascending=True)
large.head(n=5)

,ID,Name in English,Countries,Country codes alpha 3,Degree_of_endangerment,Number of speakers,Latitude,Longitude,Description of the location
0,1022,South Italian,Italy,ITA,Vulnerable,7500000.0,40.9798,15.2490,"Campania, Lucania (Basilicata), Abruzzi (Abruz..."
1,1023,Sicilian,Italy,ITA,Vulnerable,5000000.0,37.4399,14.5019,"Sicily (Sicilia), southern and central Calabri..."
2,383,Low Saxon,"Germany, Denmark, Netherlands, Poland, Russian...","DEU, DNK, NLD, POL, RUS",Vulnerable,4800000.0,53.4029,10.3601,"northern Germany, the north-eastern part of th..."
3,335,Belarusian,"Belarus, Latvia, Lithuania, Poland, Russian Fe...","BRB, LVA, LTU, POL, RUS, UKR",Vulnerable,4000000.0,53.9560,27.5756,Belarus except the Polesian-speaking south-wes...
4,382,Lombard,"Italy, Switzerland","ITA, CHE",Definitely endangered,3500000.0,45.7215,9.3273,the region of Lombardy (except the southernmos...

In [5]:
#sort in descending order
small=data.sort_values(by='Number of speakers', ascending=True)#sort in ascending order
small.head(n=10)

,ID,Name in English,Countries,Country codes alpha 3,Degree_of_endangerment,Number of speakers,Latitude,Longitude,Description of the location
2538,130,ǁXegwi,South Africa,ZAF,Extinct,0.0,-25.3500,30.9900,"Lake Chrissie, Eastern Transvaal."
2374,477,Kamas,Russian Federation,RUS,Extinct,0.0,57.9964,92.8784,formerly spoken in the eastern part of the Min...
2373,696,Judeo-Berber (Morocco),Morocco,MAR,Extinct,0.0,30.8220,-6.8005,Several areas in the Higher and the Middle Atl...
2372,1925,Jorá,Bolivia (Plurinational State of),BOL,Critically endangered,0.0,-14.0246,-63.3581,NaN
2371,857,Island Chumash,United States of America,USA,Extinct,0.0,34.3821,-119.4574,NaN
2370,298,Island Carib,Dominica,DMA,Extinct,0.0,15.4325,-61.2817,Carib Indian reservation on the eastern coast ...
2369,854,Ineseño,United States of America,USA,Extinct,0.0,34.5942,-120.1371,NaN
2368,2642,Ifo,Vanuatu,VUT,Extinct,0.0,-18.6605,169.1434,Northeastern Erromanga Island
2367,1537,Huron-Wyandot (United States of America),United States of America,USA,Extinct,0.0,36.7923,-94.7229,Huron and Wyandotte is the same language. The ...
2366,2592,Hukumina,Indonesia,IDN,Extinct,0.0,-3.1514,126.2713,"Buru Island, Maluku"

In [7]:
byStatus = data.groupby('Degree_of_endangerment') 
byStatus.head(n=5)

,ID,Name in English,Countries,Country codes alpha 3,Degree_of_endangerment,Number of speakers,Latitude,Longitude,Description of the location
0,1022,South Italian,Italy,ITA,Vulnerable,7500000.0,40.9798,15.2490,"Campania, Lucania (Basilicata), Abruzzi (Abruz..."
1,1023,Sicilian,Italy,ITA,Vulnerable,5000000.0,37.4399,14.5019,"Sicily (Sicilia), southern and central Calabri..."
2,383,Low Saxon,"Germany, Denmark, Netherlands, Poland, Russian...","DEU, DNK, NLD, POL, RUS",Vulnerable,4800000.0,53.4029,10.3601,"northern Germany, the north-eastern part of th..."
3,335,Belarusian,"Belarus, Latvia, Lithuania, Poland, Russian Fe...","BRB, LVA, LTU, POL, RUS, UKR",Vulnerable,4000000.0,53.9560,27.5756,Belarus except the Polesian-speaking south-wes...
4,382,Lombard,"Italy, Switzerland","ITA, CHE",Definitely endangered,3500000.0,45.7215,9.3273,the region of Lombardy (except the southernmos...
5,405,Romani,"Albania, Germany, Austria, Belarus, Bosnia and...","ALB, DEU, AUT, BRB, BIH, BGR, HRV, EST, FIN, F...",Definitely endangered,3500000.0,46.3165,22.3681,"many European countries, most densely in East-..."
6,2211,Yiddish (Israel),Israel,ISR,Definitely endangered,3000000.0,32.0833,34.8333,"most speakers now live outside Europe, mainly ..."
7,1586,Gondi,India,IND,Vulnerable,2713790.0,19.5804,80.4418,"Madhya Pradesh (Betul, Chhindwara, Seoni, Mand..."
12,349,Emilian-Romagnol,"Italy, San Marino","ITA, SMR",Definitely endangered,2000000.0,44.1270,12.0739,"the region of Emilia-Romagna, parts of the pro..."
13,399,Piedmontese,Italy,ITA,Definitely endangered,2000000.0,45.2013,7.8662,"Piedmont Region except the Novara Province, th..."
48,398,Picard,"Belgium, France","BEL, FRA",Severely endangered,700000.0,50.2331,2.7905,the regions of Picardy (Picardie) and Nord-Pas...
62,375,Languedocian,France,FRA,Severely endangered,500000.0,43.8899,2.5378,an area from Bordeaux in the northwest to Mont...
77,2165,Judezmo (Israel),Israel,ISR,Severely endangered,400000.0,32.0872,34.7737,resettled communities in Israel where the majo...
79,378,Limousin,France,FRA,Severely endangered,400000.0,46.0579,1.8017,"the departments of Corréze and Haute-Vienne, m..."
104,336,Breton,France,FRA,Severely endangered,250000.0,48.2246,-3.9331,western Brittany; many émigré communities
232,1587,Parji,India,IND,Critically endangered,51216.0,18.5629,82.8039,Madhya Pradesh
250,2180,Zenatiya,Algeria,DZA,Critically endangered,50000.0,35.5702,1.8099,The Ouarsenis region including the the Tissems...
307,1490,Mayo,Mexico,MEX,Critically endangered,32869.0,26.9114,-109.6271,"Municipalities of Cajeme, Etchojoa, Huatabampo..."
310,1561,Sirmaudi,India,IND,Critically endangered,31144.0,30.9823,77.1569,"Himachal Pradesh, near Shimla and Solan"
332,2181,Tidikelt,Algeria,DZA,Critically endangered,30000.0,26.8828,2.5488,Tidkilet region especially In Salah and severa...
485,2618,Tobada',Indonesia,IDN,Extinct,12000.0,-2.0190,119.4708,"On the headwaters of the Budong-Budong River, ..."
1040,2059,Tamazight (Ait Rouadi),Morocco,MAR,Extinct,1637.0,32.5745,-5.9655,Semguet et Guettaya centers of Kasbat Tadla 2...
2221,580,Canichana,Bolivia (Plurinational State of),BOL,Extinct,3.0,-14.5835,-64.9731,"San Pedro, province of Cercado, department of ..."
2269,2112,Lae,Papua New Guinea,PNG,Extinct,1.0,-6.6318,147.1810,Morobe
2277,661,Uru,Bolivia (Plurinational State of),BOL,Extinct,1.0,-16.5519,-68.6645,"Last documented community was Iru-Ito, near An..."

In [5]:
data.groupby(['Degree_of_endangerment']).count()

,ID,Name in English,Countries,Country codes alpha 3,Number of speakers,Latitude,Longitude,Description of the location
Degree_of_endangerment,,,,,,,,
Critically endangered,607,607,607,607,544,606,606,395
Definitely endangered,680,680,679,679,635,680,680,485
Extinct,253,253,253,253,244,252,252,142
Severely endangered,554,554,554,554,505,554,554,388
Vulnerable,628,628,628,628,611,627,627,460

In [6]:
#group on basis of two qualitative columns

bygroup_CnS = data.groupby(['Countries', 'Degree_of_endangerment'])

bygroup_CnS.head(10)

,ID,Name in English,Countries,Country codes alpha 3,Degree_of_endangerment,Number of speakers,Latitude,Longitude,Description of the location
0,1022,South Italian,Italy,ITA,Vulnerable,7500000.0,40.9798,15.2490,"Campania, Lucania (Basilicata), Abruzzi (Abruz..."
1,1023,Sicilian,Italy,ITA,Vulnerable,5000000.0,37.4399,14.5019,"Sicily (Sicilia), southern and central Calabri..."
2,383,Low Saxon,"Germany, Denmark, Netherlands, Poland, Russian...","DEU, DNK, NLD, POL, RUS",Vulnerable,4800000.0,53.4029,10.3601,"northern Germany, the north-eastern part of th..."
3,335,Belarusian,"Belarus, Latvia, Lithuania, Poland, Russian Fe...","BRB, LVA, LTU, POL, RUS, UKR",Vulnerable,4000000.0,53.9560,27.5756,Belarus except the Polesian-speaking south-wes...
4,382,Lombard,"Italy, Switzerland","ITA, CHE",Definitely endangered,3500000.0,45.7215,9.3273,the region of Lombardy (except the southernmos...
...,...,...,...,...,...,...,...,...,...
2714,1971,Yaeyama,Japan,JPN,Severely endangered,NaN,24.3420,124.1537,islands of the Yaeyama region
2716,428,Yiddish (Europe),"Germany, Austria, Belarus, Belgium, Denmark, E...","DEU, AUT, BRB, BEL, DNK, EST, FIN, FRA, HUN, I...",Definitely endangered,NaN,53.3571,25.2465,earlier spoken in large areas mainly in Easter...
2717,1972,Yonaguni,Japan,JPN,Severely endangered,NaN,24.4580,122.9802,Yonaguni Island
2720,2716,Zangskari,"India, Pakistan","IND, PAK",Definitely endangered,NaN,34.0833,76.8500,NaN
2721,2177,Zidgali,Oman,OMN,Critically endangered,NaN,23.4027,58.0957,Capital area of Muscat

In [7]:
data.groupby(['Countries','Degree_of_endangerment']).count()

                                                                           ID  \
Countries                                          Degree_of_endangerment
Afghanistan                                        Critically endangered    2
                                                   Definitely endangered    5
                                                   Severely endangered      4
                                                   Vulnerable               1
Albania, Algeria, Bosnia and Herzegovina, Bulga... Severely endangered      1
...                                                                        ..
Viet Nam                                           Severely endangered      2
                                                   Vulnerable               4
Western Sahara                                     Critically endangered    1
Yemen                                              Definitely endangered    1
                                                   Severely endangered      1

                                                                           Name in English  \
Countries                                          Degree_of_endangerment
Afghanistan                                        Critically endangered                 2
                                                   Definitely endangered                 5
                                                   Severely endangered                   4
                                                   Vulnerable                            1
Albania, Algeria, Bosnia and Herzegovina, Bulga... Severely endangered                   1
...                                                                                    ...
Viet Nam                                           Severely endangered                   2
                                                   Vulnerable                            4
Western Sahara                                     Critically endangered                 1
Yemen                                              Definitely endangered                 1
                                                   Severely endangered                   1

                                                                           Country codes alpha 3  \
Countries                                          Degree_of_endangerment
Afghanistan                                        Critically endangered                       2
                                                   Definitely endangered                       5
                                                   Severely endangered                         4
                                                   Vulnerable                                  1
Albania, Algeria, Bosnia and Herzegovina, Bulga... Severely endangered                         1
...                                                                                          ...
Viet Nam                                           Severely endangered                         2
                                                   Vulnerable                                  4
Western Sahara                                     Critically endangered                       1
Yemen                                              Definitely endangered                       1
                                                   Severely endangered                         1

                                                                           Number of speakers  \
Countries                                          Degree_of_endangerment
Afghanistan                                        Critically endangered                    2
                                                   Definitely endangered                    5
                                                   Severely endangered                      4
                                                   Vulnerable                               0
Albania, Algeria, Bosnia and Herzegovina, Bulga... Severely endangered                      0
...                                                                                       ...
Viet Nam                                           Severely endangered                      2
                                                   Vulnerable                               4
Western Sahara                                     Critically endangered                    1
Yemen                                              Definitely endangered                    1
                                                   Severely endangered                      1

                                                                           Latitude  \
Countries                                          Degree_of_endangerment
Afghanistan                                        Critically endangered          2
                                                   Definitely endangered          5
                                                   Severely endangered            4
                                                   Vulnerable                     1
Albania, Algeria, Bosnia and Herzegovina, Bulga... Severely endangered            1
...                                                                             ...
Viet Nam                                           Severely endangered            2
                                                   Vulnerable                     4
Western Sahara                                     Critically endangered          1
Yemen                                              Definitely endangered          1
                                                   Severely endangered            1

                                                                           Longitude  \
Countries                                          Degree_of_endangerment
Afghanistan                                        Critically endangered           2
                                                   Definitely endangered           5
                                                   Severely endangered             4
                                                   Vulnerable                      1
Albania, Algeria, Bosnia and Herzegovina, Bulga... Severely endangered             1
...                                                                              ...
Viet Nam                                           Severely endangered             2
                                                   Vulnerable                      4
Western Sahara                                     Critically endangered           1
Yemen                                              Definitely endangered           1
                                                   Severely endangered             1

                                                                           Description of the location
Countries                                          Degree_of_endangerment
Afghanistan                                        Critically endangered                             2
                                                   Definitely endangered                             5
                                                   Severely endangered                               4
                                                   Vulnerable                                        0
Albania, Algeria, Bosnia and Herzegovina, Bulga... Severely endangered                               1
...                                                                                                ...
Viet Nam                                           Severely endangered                               0
                                                   Vulnerable                                        0
Western Sahara                                     Critically endangered                             1
Yemen                                              Definitely endangered                             1
                                                   Severely endangered                               1

[531 rows x 7 columns]

In [8]:
# group number of speakers by group labels (row names) from countries

x=data['Number of speakers'].groupby(data['Countries'])
x.head()

0       7500000.0
1       5000000.0
2       4800000.0
3       4000000.0
4       3500000.0
          ...
2689          NaN
2705          NaN
2708          NaN
2713          NaN
2716          NaN
Name: Number of speakers, Length: 662, dtype: float64

### lambda functions

#### identify which languages have fewer then 5k speakers

In [9]:
data['vfew'] = data['Number of speakers'].apply(lambda x: x <= 5000)
#data['vfew'] = data['Number of speakers'].apply(lambda x: 'possible' if x <= 5000, else 'impossible')

In [18]:
data.head(n=6)

,ID,Name in English,Countries,Country codes alpha 3,Degree_of_endangerment,Number of speakers,Latitude,Longitude,Description of the location,vfew
0,1022,South Italian,Italy,ITA,Vulnerable,7500000.0,40.9798,15.2490,"Campania, Lucania (Basilicata), Abruzzi (Abruz...",False
1,1023,Sicilian,Italy,ITA,Vulnerable,5000000.0,37.4399,14.5019,"Sicily (Sicilia), southern and central Calabri...",False
2,383,Low Saxon,"Germany, Denmark, Netherlands, Poland, Russian...","DEU, DNK, NLD, POL, RUS",Vulnerable,4800000.0,53.4029,10.3601,"northern Germany, the north-eastern part of th...",False
3,335,Belarusian,"Belarus, Latvia, Lithuania, Poland, Russian Fe...","BRB, LVA, LTU, POL, RUS, UKR",Vulnerable,4000000.0,53.9560,27.5756,Belarus except the Polesian-speaking south-wes...,False
4,382,Lombard,"Italy, Switzerland","ITA, CHE",Definitely endangered,3500000.0,45.7215,9.3273,the region of Lombardy (except the southernmos...,False
5,405,Romani,"Albania, Germany, Austria, Belarus, Bosnia and...","ALB, DEU, AUT, BRB, BIH, BGR, HRV, EST, FIN, F...",Definitely endangered,3500000.0,46.3165,22.3681,"many European countries, most densely in East-...",False

In [10]:
group_by_5k = data.groupby(['vfew'])

In [11]:
group_by_5k.size()

vfew
False     879
True     1843
dtype: int64

In [12]:
group_by_5kC = data.groupby(['vfew','Countries'])

In [13]:
group_by_5kC.size()

vfew   Countries
False  Afghanistan                                                                                                                                                                                                                                                                                                                                                                                      2
       Albania, Algeria, Bosnia and Herzegovina, Bulgaria, Croatia, Greece, The former Yugoslav Republic of Macedonia, Morocco, Romania, Turkey, Serbia                                                                                                                                                                                                                                                 1
       Albania, Bulgaria, Greece, The former Yugoslav Republic of Macedonia, Serbia                                                                                                                                                                                                                                                                                                                     1
       Albania, Bulgaria, The former Yugoslav Republic of Macedonia, Romania, Serbia                                                                                                                                                                                                                                                                                                                    1
       Albania, Germany, Austria, Belarus, Bosnia and Herzegovina, Bulgaria, Croatia, Estonia, Finland, France, Greece, Hungary, Italy, Latvia, Lithuania, The former Yugoslav Republic of Macedonia, Netherlands, Poland, Romania, United Kingdom of Great Britain and Northern Ireland, Russian Federation, Slovakia, Slovenia, Switzerland, Czech Republic, Turkey, Ukraine, Serbia, Montenegro      1
                                                                                                                                                                                                                                                                                                                                                                                                     ...
True   United States of America                                                                                                                                                                                                                                                                                                                                                                       192
       Vanuatu                                                                                                                                                                                                                                                                                                                                                                                         47
       Venezuela (Bolivarian Republic of)                                                                                                                                                                                                                                                                                                                                                              18
       Viet Nam                                                                                                                                                                                                                                                                                                                                                                                        14
       Western Sahara                                                                                                                                                                                                                                                                                                                                                                                   1
Length: 346, dtype: int64

In [14]:
data['Degree_of_endangerment'].value_counts()

Degree_of_endangerment
Definitely endangered    680
Vulnerable               628
Critically endangered    607
Severely endangered      554
Extinct                  253
Name: count, dtype: int64

In [ ]:
import pandas as pd
import numpy as np

## cross-tab

In [21]:
data1 = pd.read_csv(r"D:\UNEC\python_data analytics\endangeredLang11.csv")
 
data1.head(n=6)

,ID,Name in English,Countries,Country codes alpha 3,Degree_of_endangerment,Number of speakers,Latitude,Longitude,Description of the location
0,1022,South Italian,Italy,ITA,Vulnerable,7500000.0,40.9798,15.2490,"Campania, Lucania (Basilicata), Abruzzi (Abruz..."
1,1023,Sicilian,Italy,ITA,Vulnerable,5000000.0,37.4399,14.5019,"Sicily (Sicilia), southern and central Calabri..."
2,383,Low Saxon,"Germany, Denmark, Netherlands, Poland, Russian...","DEU, DNK, NLD, POL, RUS",Vulnerable,4800000.0,53.4029,10.3601,"northern Germany, the north-eastern part of th..."
3,335,Belarusian,"Belarus, Latvia, Lithuania, Poland, Russian Fe...","BRB, LVA, LTU, POL, RUS, UKR",Vulnerable,4000000.0,53.9560,27.5756,Belarus except the Polesian-speaking south-wes...
4,382,Lombard,"Italy, Switzerland","ITA, CHE",Definitely endangered,3500000.0,45.7215,9.3273,the region of Lombardy (except the southernmos...
5,405,Romani,"Albania, Germany, Austria, Belarus, Bosnia and...","ALB, DEU, AUT, BRB, BIH, BGR, HRV, EST, FIN, F...",Definitely endangered,3500000.0,46.3165,22.3681,"many European countries, most densely in East-..."

In [30]:
x=pd.crosstab(data1["Countries"],data1["Latitude"],margins=True) #tabulate our data on basis of two coulmns

In [31]:
x.head(4)

Latitude,-55.0028,-54.6229,-51.5087,-49.6391,-43.4848,-40.4803,-40.0791,-38.5653,-38.4105,-35.4964,...,69.2872,69.3878,69.4386,69.5333,71.2725,71.3851,71.6973,72.816,77.4815,All
Countries,,,,,,,,,,,,,,,,,,,,,
Afghanistan,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,12
"Albania, Algeria, Bosnia and Herzegovina, Bulgaria, Croatia, Greece, The former Yugoslav Republic of Macedonia, Morocco, Romania, Turkey, Serbia",0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
"Albania, Bulgaria, Greece, The former Yugoslav Republic of Macedonia, Serbia",0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
"Albania, Bulgaria, The former Yugoslav Republic of Macedonia, Romania, Serbia",0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [32]:
def perConvert(var):
    return var/float(var[-1])

In [33]:
x=pd.crosstab(data1["Countries"],data1["Latitude"],margins=True).apply(perConvert, axis=1)

C:\Users\hp\AppData\Local\Temp\ipykernel_31320\3694094084.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  return var/float(var[-1])

In [34]:
x.head(3)

Latitude,-55.0028,-54.6229,-51.5087,-49.6391,-43.4848,-40.4803,-40.0791,-38.5653,-38.4105,-35.4964,...,69.2872,69.3878,69.4386,69.5333,71.2725,71.3851,71.6973,72.816,77.4815,All
Countries,,,,,,,,,,,,,,,,,,,,,
Afghanistan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
"Albania, Algeria, Bosnia and Herzegovina, Bulgaria, Croatia, Greece, The former Yugoslav Republic of Macedonia, Morocco, Romania, Turkey, Serbia",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
"Albania, Bulgaria, Greece, The former Yugoslav Republic of Macedonia, Serbia",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

## Reshaping

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv(r"D:\UNEC\python_data analytics\endangeredLang11.csv")
 
data.head(n=6)

,ID,Name in English,Countries,Country codes alpha 3,Degree of endangerment,Number of speakers,Latitude,Longitude,Description of the location
0,1022,South Italian,Italy,ITA,Vulnerable,7500000.0,40.9798,15.2490,"Campania, Lucania (Basilicata), Abruzzi (Abruz..."
1,1023,Sicilian,Italy,ITA,Vulnerable,5000000.0,37.4399,14.5019,"Sicily (Sicilia), southern and central Calabri..."
2,383,Low Saxon,"Germany, Denmark, Netherlands, Poland, Russian...","DEU, DNK, NLD, POL, RUS",Vulnerable,4800000.0,53.4029,10.3601,"northern Germany, the north-eastern part of th..."
3,335,Belarusian,"Belarus, Latvia, Lithuania, Poland, Russian Fe...","BRB, LVA, LTU, POL, RUS, UKR",Vulnerable,4000000.0,53.9560,27.5756,Belarus except the Polesian-speaking south-wes...
4,382,Lombard,"Italy, Switzerland","ITA, CHE",Definitely endangered,3500000.0,45.7215,9.3273,the region of Lombardy (except the southernmos...
5,405,Romani,"Albania, Germany, Austria, Belarus, Bosnia and...","ALB, DEU, AUT, BRB, BIH, BGR, HRV, EST, FIN, F...",Definitely endangered,3500000.0,46.3165,22.3681,"many European countries, most densely in East-..."

In [ ]:
dstack=data.stack() #pivot the columns as rows for each ID
#columns become row labels
dstack

0     ID                                               1022
      Name in English                         South Italian
      Countries                                       Italy
      Country codes alpha 3                             ITA
      Degree of endangerment                     Vulnerable
                                              ...
2721  Country codes alpha 3                             OMN
      Degree of endangerment          Critically endangered
      Latitude                                      23.4027
      Longitude                                     58.0957
      Description of the location    Capital area of Muscat
Length: 23455, dtype: object

In [ ]:
x=dstack.unstack()  #unstack the previous

x.head(4)

,ID,Name in English,Countries,Country codes alpha 3,Degree of endangerment,Number of speakers,Latitude,Longitude,Description of the location
0,1022,South Italian,Italy,ITA,Vulnerable,7500000.0,40.9798,15.249,"Campania, Lucania (Basilicata), Abruzzi (Abruz..."
1,1023,Sicilian,Italy,ITA,Vulnerable,5000000.0,37.4399,14.5019,"Sicily (Sicilia), southern and central Calabri..."
2,383,Low Saxon,"Germany, Denmark, Netherlands, Poland, Russian...","DEU, DNK, NLD, POL, RUS",Vulnerable,4800000.0,53.4029,10.3601,"northern Germany, the north-eastern part of th..."
3,335,Belarusian,"Belarus, Latvia, Lithuania, Poland, Russian Fe...","BRB, LVA, LTU, POL, RUS, UKR",Vulnerable,4000000.0,53.956,27.5756,Belarus except the Polesian-speaking south-wes...

### melting

In [ ]:
patient = pd.DataFrame({'FirstName' : ['Bill', 'Jane'],
                       'LastName' : ['Shakespeare', 'Austen'],
                       'BloodType' : ['o+', 'B+'],
                       'Wt' : [85, 62]})

patient

  FirstName     LastName BloodType  Wt
0      Bill  Shakespeare        o+  85
1      Jane       Austen        B+  62

In [ ]:
# Use `melt()
#you have a data that has one or more columns that are identifier variables, 
#while all other columns are considered measured variables
print(pd.melt(patient, id_vars=['FirstName', 'LastName'], var_name='measurements'))

  FirstName     LastName measurements value
0      Bill  Shakespeare    BloodType    o+
1      Jane       Austen    BloodType    B+
2      Bill  Shakespeare           Wt    85
3      Jane       Austen           Wt    62

In [154]:
x=data[0:15]
x.head(3)

,ID,Name in English,Countries,Country codes alpha 3,Degree of endangerment,Number of speakers,Latitude,Longitude,Description of the location
0,1022,South Italian,Italy,ITA,Vulnerable,7500000.0,40.9798,15.2490,"Campania, Lucania (Basilicata), Abruzzi (Abruz..."
1,1023,Sicilian,Italy,ITA,Vulnerable,5000000.0,37.4399,14.5019,"Sicily (Sicilia), southern and central Calabri..."
2,383,Low Saxon,"Germany, Denmark, Netherlands, Poland, Russian...","DEU, DNK, NLD, POL, RUS",Vulnerable,4800000.0,53.4029,10.3601,"northern Germany, the north-eastern part of th..."

In [155]:
x=x.drop('ID',axis=1) #drop ID column

In [156]:
x.head(4)

,Name in English,Countries,Country codes alpha 3,Degree of endangerment,Number of speakers,Latitude,Longitude,Description of the location
0,South Italian,Italy,ITA,Vulnerable,7500000.0,40.9798,15.2490,"Campania, Lucania (Basilicata), Abruzzi (Abruz..."
1,Sicilian,Italy,ITA,Vulnerable,5000000.0,37.4399,14.5019,"Sicily (Sicilia), southern and central Calabri..."
2,Low Saxon,"Germany, Denmark, Netherlands, Poland, Russian...","DEU, DNK, NLD, POL, RUS",Vulnerable,4800000.0,53.4029,10.3601,"northern Germany, the north-eastern part of th..."
3,Belarusian,"Belarus, Latvia, Lithuania, Poland, Russian Fe...","BRB, LVA, LTU, POL, RUS, UKR",Vulnerable,4000000.0,53.9560,27.5756,Belarus except the Polesian-speaking south-wes...

In [ ]:
x.drop(['EnglishNames', 'CountryCode','Latitude','Longitude'], axis=1, inplace=True) #drop multiple coulmns

In [ ]:
x.head(4)

                                           Countries Endangerment         No
0                                              Italy   Vulnerable  7500000.0
1                                              Italy   Vulnerable  5000000.0
2  Germany, Denmark, Netherlands, Poland, Russian...   Vulnerable  4800000.0
3  Belarus, Latvia, Lithuania, Poland, Russian Fe...   Vulnerable  4000000.0

In [ ]:
melted = pd.melt(x, id_vars=["Countries","Endangerment"], value_name="No")
melted

,Countries,Endangerment,variable,No
0,Italy,Vulnerable,No,7500000.0
1,Italy,Vulnerable,No,5000000.0
2,"Germany, Denmark, Netherlands, Poland, Russian...",Vulnerable,No,4800000.0
3,"Belarus, Latvia, Lithuania, Poland, Russian Fe...",Vulnerable,No,4000000.0
4,"Italy, Switzerland",Definitely endangered,No,3500000.0
5,"Albania, Germany, Austria, Belarus, Bosnia and...",Definitely endangered,No,3500000.0
6,Israel,Definitely endangered,No,3000000.0
7,India,Vulnerable,No,2713790.0
8,"Germany, Belgium, Netherlands",Vulnerable,No,2600000.0
9,Bolivia (Plurinational State of),Vulnerable,No,2300000.0
10,"India, Nepal",Vulnerable,No,2003783.0
11,"Bolivia (Plurinational State of), Chile, Peru",Vulnerable,No,2000000.0
12,"Italy, San Marino",Definitely endangered,No,2000000.0
13,Italy,Definitely endangered,No,2000000.0
14,"Croatia, Italy, Slovenia",Vulnerable,No,2000000.0

In [ ]:
melted = pd.melt(x, id_vars=["Countries"],var_name="Endangerment", value_name="No") # “var_name” variables will turn rows into
#columns
melted

,Countries,Endangerment,No
0,Italy,Endangerment,Vulnerable
1,Italy,Endangerment,Vulnerable
2,"Germany, Denmark, Netherlands, Poland, Russian...",Endangerment,Vulnerable
3,"Belarus, Latvia, Lithuania, Poland, Russian Fe...",Endangerment,Vulnerable
4,"Italy, Switzerland",Endangerment,Definitely endangered
5,"Albania, Germany, Austria, Belarus, Bosnia and...",Endangerment,Definitely endangered
6,Israel,Endangerment,Definitely endangered
7,India,Endangerment,Vulnerable
8,"Germany, Belgium, Netherlands",Endangerment,Vulnerable
9,Bolivia (Plurinational State of),Endangerment,Vulnerable
10,"India, Nepal",Endangerment,Vulnerable
11,"Bolivia (Plurinational State of), Chile, Peru",Endangerment,Vulnerable
12,"Italy, San Marino",Endangerment,Definitely endangered
13,Italy,Endangerment,Definitely endangered
14,"Croatia, Italy, Slovenia",Endangerment,Vulnerable
15,Italy,No,7.5e+06
16,Italy,No,5e+06
17,"Germany, Denmark, Netherlands, Poland, Russian...",No,4.8e+06
18,"Belarus, Latvia, Lithuania, Poland, Russian Fe...",No,4e+06
19,"Italy, Switzerland",No,3.5e+06
20,"Albania, Germany, Austria, Belarus, Bosnia and...",No,3.5e+06
21,Israel,No,3e+06
22,India,No,2.71379e+06
23,"Germany, Belgium, Netherlands",No,2.6e+06
24,Bolivia (Plurinational State of),No,2.3e+06
25,"India, Nepal",No,2.00378e+06
26,"Bolivia (Plurinational State of), Chile, Peru",No,2e+06
27,"Italy, San Marino",No,2e+06
28,Italy,No,2e+06
29,"Croatia, Italy, Slovenia",No,2e+06

## Pivoting

### Create a new derived table out of an existing one
### specify an index or indices to pivot on
### Reshape data  based on column values. 
### Uses unique values from index / columns

In [1]:
import pandas as pd
import numpy as np

In [32]:
data = pd.read_csv(r"D:\UNEC\python_data analytics\endangeredLang11.csv")
 
data.head(4)

,ID,Name in English,Countries,Country codes alpha 3,Degree_of_endangerment,Number of speakers,Latitude,Longitude,Description of the location
0,1022,South Italian,Italy,ITA,Vulnerable,7500000.0,40.9798,15.2490,"Campania, Lucania (Basilicata), Abruzzi (Abruz..."
1,1023,Sicilian,Italy,ITA,Vulnerable,5000000.0,37.4399,14.5019,"Sicily (Sicilia), southern and central Calabri..."
2,383,Low Saxon,"Germany, Denmark, Netherlands, Poland, Russian...","DEU, DNK, NLD, POL, RUS",Vulnerable,4800000.0,53.4029,10.3601,"northern Germany, the north-eastern part of th..."
3,335,Belarusian,"Belarus, Latvia, Lithuania, Poland, Russian Fe...","BRB, LVA, LTU, POL, RUS, UKR",Vulnerable,4000000.0,53.9560,27.5756,Belarus except the Polesian-speaking south-wes...

In [59]:
# p=pd.pivot_table(data,index=["Countries"], aggfunc='sum') #specify a unique index
#ISO3 is a column with all unique values

In [56]:
p.head(5)

,Country codes alpha 3,Degree_of_endangerment,Description of the location,ID,Latitude,Longitude,Name in English,Number of speakers
Countries,,,,,,,,
Afghanistan,AFGAFGAFGAFGAFGAFGAFGAFGAFGAFGAFGAFG,Definitely endangeredDefinitely endangeredSeve...,"Villages in Nijrau,Tagau, Pachaghan, Shutul, G...",18959,418.5402,838.5071,ParachiAshkunMunjiPrasunWaigaliWotapuri-Katarq...,18500.0
"Albania, Algeria, Bosnia and Herzegovina, Bulgaria, Croatia, Greece, The former Yugoslav Republic of Macedonia, Morocco, Romania, Turkey, Serbia","ALB, DZA, BIH, BGR, HRV, GRC, MKD, MAR, ROU, T...",Severely endangered,"traditionally Greece and Turkey, primarily in ...",374,41.2607,28.4985,Judezmo (Europe),0.0
"Albania, Bulgaria, Greece, The former Yugoslav Republic of Macedonia, Serbia","ALB, BGR, GRC, MKD, SRB",Definitely endangered,Thessaly and Epirus in northern Greece; the ce...,331,40.2292,21.1376,Aromanian,500000.0
"Albania, Bulgaria, The former Yugoslav Republic of Macedonia, Romania, Serbia","ALB, BGR, MKD, ROU, SRB",Vulnerable,"the core area: south-eastern Serbia, the weste...",1026,42.9644,22.1374,Torlak,1500000.0
"Albania, Germany, Austria, Belarus, Bosnia and Herzegovina, Bulgaria, Croatia, Estonia, Finland, France, Greece, Hungary, Italy, Latvia, Lithuania, The former Yugoslav Republic of Macedonia, Netherlands, Poland, Romania, United Kingdom of Great Britain and Northern Ireland, Russian Federation, Slovakia, Slovenia, Switzerland, Czech Republic, Turkey, Ukraine, Serbia, Montenegro","ALB, DEU, AUT, BRB, BIH, BGR, HRV, EST, FIN, F...",Definitely endangered,"many European countries, most densely in East-...",405,46.3165,22.3681,Romani,3500000.0

In [62]:
p=pd.pivot_table(data, index=["Country","ISO3"]) #specify tow column indices with unique values to pivot on

KeyError: 'Country'

In [ ]:
p.head(4)

,,Active Personnel,Aircraft Carriers,Armored Fighting Vehicles,Attack Aircraft,Attack Helicopters,Combat Tanks,Consumption (bbl/dy),Corvettes,Defense Budget,Destroyers,...,Square Land Area (km),Submarines,Total Aircraft Strength,Total Helicopter Strength,Total Military Personnel,Total Naval Assets,Total Population,Towed Artillery,Trainer Aircraft,Transport Aircraft
Country,ISO3,,,,,,,,,,,,,,,,,,,,,
Afghanistan,AFG,200000,0,9562,15,6,0,50000,0,11500,0,...,652230,0,205,142,200000,0,33332025,200,0,158
Albania,ALB,50000,0,933,0,0,0,40000,0,110,0,...,28748,0,23,23,64000,38,3038594,0,0,23
Algeria,ALG,520000,0,6754,99,38,2405,350000,13,10570,0,...,2381741,6,502,257,792350,85,40263711,270,68,266
Angola,ANG,107000,0,538,78,15,244,133000,0,4150,0,...,1246700,0,285,118,175500,57,20172332,332,48,128

In [67]:
p=pd.pivot_table(data, index=["Country","ISO3"], values=["Attack Helicopters"]) #include the corrsponding values

KeyError: 'Attack Helicopters'

In [ ]:
p.head(4)

                  Attack Aircraft
Country     ISO3
Afghanistan AFG                15
Albania     ALB                 0
Algeria     ALG                99
Angola      ANG                78

In [68]:
p=pd.pivot_table(data,index=["Country","ISO3","Rank"],values=["Attack Aircraft","Active Personnel"]) #3 indices to pivot on 
#input 2 values

KeyError: 'Attack Aircraft'

In [ ]:
p.tail(8)

                         Active Personnel  Attack Aircraft
Country       ISO3 Rank
United States USA  1              1373650             2785
Uruguay       URU  104              25000               13
Uzbekistan    UZB  48               56500               89
Venezuela     VEN  45              115000               33
Vietnam       VTN  16              448500               73
Yemen         YEM  64               43500               77
Zambia        ZAM  85               15100               18
Zimbabwe      ZIM  81               30000               10

In [ ]:
## Pivoting with column indices that have non-unique values

In [71]:
df = pd.read_csv(r"D:\UNEC\python_data analytics\endangeredLang2.csv")
 
df.head(n=6)

,ID,EnglishNames,Countries,CountryCode,Endangerment,No,Latitude,Longitude
0,1022,South Italian,Italy,ITA,Vulnerable,7500000.0,40.9798,15.2490
1,1023,Sicilian,Italy,ITA,Vulnerable,5000000.0,37.4399,14.5019
2,383,Low Saxon,"Germany, Denmark, Netherlands, Poland, Russian...","DEU, DNK, NLD, POL, RUS",Vulnerable,4800000.0,53.4029,10.3601
3,335,Belarusian,"Belarus, Latvia, Lithuania, Poland, Russian Fe...","BRB, LVA, LTU, POL, RUS, UKR",Vulnerable,4000000.0,53.9560,27.5756
4,382,Lombard,"Italy, Switzerland","ITA, CHE",Definitely endangered,3500000.0,45.7215,9.3273
5,405,Romani,"Albania, Germany, Austria, Belarus, Bosnia and...","ALB, DEU, AUT, BRB, BIH, BGR, HRV, EST, FIN, F...",Definitely endangered,3500000.0,46.3165,22.3681

In [72]:
import numpy as np

In [82]:
x=pd.pivot_table(df, index=['CountryCode','Endangerment'], aggfunc=np.sum) # sum endangered languages according to country 
#endangered status

C:\Users\hp\AppData\Local\Temp\ipykernel_13584\2751481663.py:1: FutureWarning: The provided callable <function sum at 0x0000021D626B13A0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  x=pd.pivot_table(df, index=['CountryCode','Endangerment'], aggfunc=np.sum) # sum endangered languages according to country

In [81]:
x

                                                      No
CountryCode             Endangerment
AFG                     Critically endangered      150.0
                        Definitely endangered     2800.0
                        Severely endangered       1050.0
ALB, BGR, GRC, MKD, SRB Definitely endangered   500000.0
ALB, BGR, MKD, ROU, SRB Vulnerable             1500000.0
...                                                  ...
ZAF                     Extinct                      0.0
ZAI                     Critically endangered       10.0
                        Extinct                      0.0
                        Severely endangered       1000.0
ZAI, SDN                Critically endangered      494.0

[500 rows x 1 columns]

In [84]:
x=pd.pivot_table(df, index=['CountryCode','Endangerment'],values=['No'], aggfunc=np.sum) # sum endangered languages according to country 
#endangered status

C:\Users\hp\AppData\Local\Temp\ipykernel_13584\1556771840.py:1: FutureWarning: The provided callable <function sum at 0x0000021D626B13A0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  x=pd.pivot_table(df, index=['CountryCode','Endangerment'],values=['No'], aggfunc=np.sum) # sum endangered languages according to country

In [85]:
x

                                                     No
CountryCode             Endangerment
AFG                     Critically endangered     300.0
                        Definitely endangered   14000.0
                        Severely endangered      4200.0
                        Vulnerable                  0.0
ALB, BGR, GRC, MKD, SRB Definitely endangered  500000.0
...                                                 ...
ZAF                     Extinct                     0.0
ZAI                     Critically endangered      10.0
                        Extinct                     0.0
                        Severely endangered      2000.0
ZAI, SDN                Critically endangered     494.0

[531 rows x 1 columns]

## Rank & Sorting

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
s=pd.Series(range(4),index=['d','a','b','c'])

In [ ]:
s

d    0
a    1
b    2
c    3
dtype: int64

In [ ]:
s.sort_index() #sort index from a to d

a    1
b    2
c    3
d    0
dtype: int64

In [ ]:
data = pd.read_csv('GlobalFirePower.csv')
 
data.head(5)

,Country,ISO3,Rank,Total Population,Manpower Available,Fit-for-Service,Reaching Military Age,Total Military Personnel,Active Personnel,Reserve Personnel,...,Railway Coverage (km),Serivecable Airports,Defense Budget,External Debt,Foreign Exchange / Gold,Purchasing Power Parity,Square Land Area (km),Coastline (km),Shared Borders (km),Waterways (km)
0,United States,USA,1,323995528,145215000,120025000,4220000,2363675,1373650,990025,...,224792,13513,587800,17910000,117600,18560000,9826675,19924,12048,41009
1,Russia,RUS,2,142355415,70000000,47000000,1355000,3371027,798527,2572500,...,87157,1218,44600,514800,365500,3745000,17098242,37653,22408,102000
2,China,CHN,3,1373541278,750000000,619000000,19550000,3712500,2260000,1452500,...,86000,507,161700,983500,3092000,21270000,9596961,14500,22457,110000
3,India,IND,4,1266883598,616000000,489600000,22900000,4207250,1362500,2844750,...,63974,346,51000,507000,359100,8721000,3287263,7000,13888,14500
4,France,FRA,5,66836154,30000000,23750000,775000,387635,204000,183635,...,29640,464,35000,5360000,138200,2737000,643801,4853,4072,8501

In [ ]:
x=data.sort_index(axis=1) #index according to columns. Coulmns will be arranged alphabetically
#default ascending

In [ ]:
x.head(4)

,Active Personnel,Aircraft Carriers,Armored Fighting Vehicles,Attack Aircraft,Attack Helicopters,Coastline (km),Combat Tanks,Consumption (bbl/dy),Corvettes,Country,...,Submarines,Total Aircraft Strength,Total Helicopter Strength,Total Military Personnel,Total Naval Assets,Total Population,Towed Artillery,Trainer Aircraft,Transport Aircraft,Waterways (km)
0,1373650,19,41062,2785,947,19924,5884,19000000,0,United States,...,70,13762,6065,2363675,415,323995528,1299,2831,5739,41009
1,798527,1,31298,1438,490,37653,20216,3320000,81,Russia,...,63,3794,1389,3371027,352,142355415,4625,387,1124,102000
2,2260000,1,4788,1385,206,14500,6457,10120000,35,China,...,68,2955,912,3712500,714,1373541278,6246,352,782,110000
3,1362500,3,6704,809,16,7000,4426,3510000,23,India,...,15,2102,666,4207250,295,1266883598,7414,323,857,14500

In [ ]:
x=data.sort_index(axis=1,ascending=False) #index according to columns. Coulmns will be arranged Z-A
#descending

In [ ]:
x.head(4)

,Waterways (km),Transport Aircraft,Trainer Aircraft,Towed Artillery,Total Population,Total Naval Assets,Total Military Personnel,Total Helicopter Strength,Total Aircraft Strength,Submarines,...,Country,Corvettes,Consumption (bbl/dy),Combat Tanks,Coastline (km),Attack Helicopters,Attack Aircraft,Armored Fighting Vehicles,Aircraft Carriers,Active Personnel
0,41009,5739,2831,1299,323995528,415,2363675,6065,13762,70,...,United States,0,19000000,5884,19924,947,2785,41062,19,1373650
1,102000,1124,387,4625,142355415,352,3371027,1389,3794,63,...,Russia,81,3320000,20216,37653,490,1438,31298,1,798527
2,110000,782,352,6246,1373541278,714,3712500,912,2955,68,...,China,35,10120000,6457,14500,206,1385,4788,1,2260000
3,14500,857,323,7414,1266883598,295,4207250,666,2102,15,...,India,23,3510000,4426,7000,16,809,6704,3,1362500

In [ ]:
x=data.sort_values(by="ISO3") #countries alphabetically A-Z (ascending order)

In [ ]:
x.head(4)

,Country,ISO3,Rank,Total Population,Manpower Available,Fit-for-Service,Reaching Military Age,Total Military Personnel,Active Personnel,Reserve Personnel,...,Railway Coverage (km),Serivecable Airports,Defense Budget,External Debt,Foreign Exchange / Gold,Purchasing Power Parity,Square Land Area (km),Coastline (km),Shared Borders (km),Waterways (km)
68,Afghanistan,AFG,69,33332025,14000000,8000000,765000,200000,200000,0,...,0,43,11500,1280,66810,64080,652230,Landlocked,5987,1200
89,Albania,ALB,90,3038594,1515000,1300000,62000,64000,50000,14000,...,339,4,110,7797,3213,34210,28748,362,691,41
24,Algeria,ALG,25,40263711,20400000,17250000,675000,792350,520000,272350,...,3973,157,10570,5934,115000,609400,2381741,998,6734,Minimum not met.
50,Angola,ANG,51,20172332,6030000,3040000,310000,175500,107000,68500,...,2764,176,4150,37700,20430,187300,1246700,1600,5369,1300

In [ ]:
x=data.sort_values(by="Rank",ascending=False) #sort by descending rank order

In [ ]:
x.head(4)

,Country,ISO3,Rank,Total Population,Manpower Available,Fit-for-Service,Reaching Military Age,Total Military Personnel,Active Personnel,Reserve Personnel,...,Railway Coverage (km),Serivecable Airports,Defense Budget,External Debt,Foreign Exchange / Gold,Purchasing Power Parity,Square Land Area (km),Coastline (km),Shared Borders (km),Waterways (km)
132,Bhutan,BUT,133,750125,175000,104300,4100,7500,7500,0,...,0,2,10,2261,15,6432,38394,Landlocked,1136,Minimum not met.
131,Suriname,SUR,132,585824,131700,77100,3030,2270,2170,100,...,0,55,67,1439,393,8547,163820,386,1907,1200
130,Sierra Leone,SIE,131,6018888,1402400,835830,32848,10750,10750,0,...,0,8,13,1561,2332,10640,71740,402,1093,800
129,Mauritania,MAU,130,3677293,1523335,1061515,72942,20870,15870,5000,...,728,30,39,3585000,1186,16710,1030700,754,5002,Minimum not met.

In [ ]:
x=data.sort_values(by=["ISO3","Country"])

In [ ]:
x.head(4)

,Country,ISO3,Rank,Total Population,Manpower Available,Fit-for-Service,Reaching Military Age,Total Military Personnel,Active Personnel,Reserve Personnel,...,Railway Coverage (km),Serivecable Airports,Defense Budget,External Debt,Foreign Exchange / Gold,Purchasing Power Parity,Square Land Area (km),Coastline (km),Shared Borders (km),Waterways (km)
68,Afghanistan,AFG,69,33332025,14000000,8000000,765000,200000,200000,0,...,0,43,11500,1280,66810,64080,652230,Landlocked,5987,1200
89,Albania,ALB,90,3038594,1515000,1300000,62000,64000,50000,14000,...,339,4,110,7797,3213,34210,28748,362,691,41
24,Algeria,ALG,25,40263711,20400000,17250000,675000,792350,520000,272350,...,3973,157,10570,5934,115000,609400,2381741,998,6734,Minimum not met.
50,Angola,ANG,51,20172332,6030000,3040000,310000,175500,107000,68500,...,2764,176,4150,37700,20430,187300,1246700,1600,5369,1300

### rank

In [ ]:
x=data.rank(axis=1) #Rank data column wise
#ascending

In [ ]:
x.head(4)

,Country,ISO3,Rank,Total Population,Manpower Available,Fit-for-Service,Reaching Military Age,Total Military Personnel,Active Personnel,Reserve Personnel,...,Railway Coverage (km),Serivecable Airports,Defense Budget,External Debt,Foreign Exchange / Gold,Purchasing Power Parity,Square Land Area (km),Coastline (km),Shared Borders (km),Waterways (km)
0,47.0,46.0,2.0,42.0,40.0,39.0,32.0,31.0,30.0,29.0,...,27.0,23.0,28.0,36.0,26.0,37.0,35.0,44.0,22.0,45.0
1,47.0,46.0,2.0,42.0,40.0,39.0,32.0,35.0,30.0,33.0,...,27.0,16.0,26.0,29.0,28.0,36.0,38.0,45.0,24.0,44.0
2,47.0,46.0,2.0,42.0,40.0,39.0,37.0,32.0,30.0,29.0,...,26.0,12.0,27.0,28.0,31.0,38.0,35.0,45.0,25.0,44.0
3,47.0,46.0,2.0,42.0,41.0,39.0,38.0,36.0,31.0,32.0,...,27.0,16.0,26.0,29.0,28.0,37.0,33.0,45.0,25.0,44.0

In [ ]:
data.head(4)

,Country,ISO3,Rank,Total Population,Manpower Available,Fit-for-Service,Reaching Military Age,Total Military Personnel,Active Personnel,Reserve Personnel,...,Railway Coverage (km),Serivecable Airports,Defense Budget,External Debt,Foreign Exchange / Gold,Purchasing Power Parity,Square Land Area (km),Coastline (km),Shared Borders (km),Waterways (km)
0,United States,USA,1,323995528,145215000,120025000,4220000,2363675,1373650,990025,...,224792,13513,587800,17910000,117600,18560000,9826675,19924,12048,41009
1,Russia,RUS,2,142355415,70000000,47000000,1355000,3371027,798527,2572500,...,87157,1218,44600,514800,365500,3745000,17098242,37653,22408,102000
2,China,CHN,3,1373541278,750000000,619000000,19550000,3712500,2260000,1452500,...,86000,507,161700,983500,3092000,21270000,9596961,14500,22457,110000
3,India,IND,4,1266883598,616000000,489600000,22900000,4207250,1362500,2844750,...,63974,346,51000,507000,359100,8721000,3287263,7000,13888,14500

In [ ]:
x=data.iloc[0:8,0:8]

In [ ]:
x.head(5)

,Country,ISO3,Rank,Total Population,Manpower Available,Fit-for-Service,Reaching Military Age,Total Military Personnel
0,United States,USA,1,323995528,145215000,120025000,4220000,2363675
1,Russia,RUS,2,142355415,70000000,47000000,1355000,3371027
2,China,CHN,3,1373541278,750000000,619000000,19550000,3712500
3,India,IND,4,1266883598,616000000,489600000,22900000,4207250
4,France,FRA,5,66836154,30000000,23750000,775000,387635

In [ ]:
x['mRank'] = x['Fit-for-Service'].rank(ascending=1)

In [ ]:
x.head(6)

,Country,ISO3,Rank,Total Population,Manpower Available,Fit-for-Service,Reaching Military Age,Total Military Personnel,mRank
0,United States,USA,1,323995528,145215000,120025000,4220000,2363675,6.0
1,Russia,RUS,2,142355415,70000000,47000000,1355000,3371027,5.0
2,China,CHN,3,1373541278,750000000,619000000,19550000,3712500,8.0
3,India,IND,4,1266883598,616000000,489600000,22900000,4207250,7.0
4,France,FRA,5,66836154,30000000,23750000,775000,387635,1.0
5,United Kingdom,UKD,6,64430428,30000000,24040000,750000,232675,2.0

## concatenate

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df1 = pd.DataFrame([['a', 1], ['b', 2]],
                  columns=['letter', 'number'])

df1

  letter  number
0      a       1
1      b       2

In [ ]:
df2 = pd.DataFrame([['c', 3], ['d', 4]],
                   columns=['letter', 'number'])
df2

  letter  number
0      c       3
1      d       4

In [ ]:
df3 = pd.DataFrame([['c', 3, 'cat'], ['d', 4, 'dog']],
                    columns=['letter', 'number', 'animal'])
df3

  letter  number animal
0      c       3    cat
1      d       4    dog

In [ ]:
pd.concat([df1, df2]) #stitch the data together, one on top of the other

  letter  number
0      a       1
1      b       2
0      c       3
1      d       4

In [ ]:
pd.concat([df1, df3])

  animal letter  number
0    NaN      a       1
1    NaN      b       2
0    cat      c       3
1    dog      d       4

In [ ]:
pd.concat([df1, df3], join="inner") #only columns common for both data frames are joined togther

  letter  number
0      a       1
1      b       2
0      c       3
1      d       4

In [50]:
drink = pd.read_csv(r'D:\UNEC\python_data analytics\starbucks-menu-nutrition-drinks.csv')
 
drink.head(5)

,Unnamed: 0,Calories,Fat (g),Carb. (g),Fiber (g),Protein,Sodium
0,Cool Lime Starbucks Refreshers™ Beverage,45,0,11,0,0,10
1,Ombré Pink Drink,-,-,-,-,-,-
2,Pink Drink,-,-,-,-,-,-
3,Strawberry Acai Starbucks Refreshers™ Beverage,80,0,18,1,0,10
4,Very Berry Hibiscus Starbucks Refreshers™ Beve...,60,0,14,1,0,10

In [54]:
file_encoding = 'cp1252'

food=pd.read_csv(r'D:\UNEC\python_data analytics\starbucks_food.csv', encoding=file_encoding)

food.head(5)

         Unnamed: 0   Calories   Fat (g)   Carb. (g)   Fiber (g)   Protein (g)
0      Chonga Bagel        300       5.0          50           3            12
1       Grain Roll8        380       6.0          70           7            10
2  Almond Croissant        410      22.0          45           3            10
3     Apple Fritter        460      23.0          56           2             7
4  Banana Nut Bread        420      22.0          52           2             6

In [55]:
pd.concat([drink, food])

,Unnamed: 0,Calories,Fat (g),Carb. (g),Fiber (g),Protein,Sodium,Calories,Fat (g),Carb. (g),Fiber (g),Protein (g)
0,Cool Lime Starbucks Refreshers™ Beverage,45,0,11,0,0,10,NaN,NaN,NaN,NaN,NaN
1,Ombré Pink Drink,-,-,-,-,-,-,NaN,NaN,NaN,NaN,NaN
2,Pink Drink,-,-,-,-,-,-,NaN,NaN,NaN,NaN,NaN
3,Strawberry Acai Starbucks Refreshers™ Beverage,80,0,18,1,0,10,NaN,NaN,NaN,NaN,NaN
4,Very Berry Hibiscus Starbucks Refreshers™ Beve...,60,0,14,1,0,10,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
108,Justin's Chocolate Hazelnut Butter,NaN,NaN,NaN,NaN,NaN,NaN,180.0,14.0,12.0,3.0,4.0
109,Justin's Classic Almond Butter,NaN,NaN,NaN,NaN,NaN,NaN,190.0,18.0,6.0,3.0,7.0
110,Lemon Chiffon Yogurt,NaN,NaN,NaN,NaN,NaN,NaN,340.0,13.0,38.0,0.0,18.0
111,Organic Avocado (Spread),NaN,NaN,NaN,NaN,NaN,NaN,90.0,8.0,5.0,4.0,1.0
112,Seasonal Fruit Blend,NaN,NaN,NaN,NaN,NaN,NaN,90.0,0.0,24.0,4.0,1.0

In [ ]:
pd.concat([drink, food], join="inner") #it will only concatenate the common columns

                                            Unnamed: 0
0             Cool Lime Starbucks Refreshers™ Beverage
1                                     Ombré Pink Drink
2                                           Pink Drink
3       Strawberry Acai Starbucks Refreshers™ Beverage
4    Very Berry Hibiscus Starbucks Refreshers™ Beve...
5                                         Violet Drink
6      Evolution Fresh™ Cold-Pressed Apple Berry Juice
7                          Evolution Fresh™ Defense Up
8              Evolution Fresh™ Organic Ginger Limeade
9                                          Iced Coffee
10                               Iced Coffee with Milk
11              Iced Espresso Classics - Vanilla Latte
12                Iced Espresso Classics - Caffe Mocha
13          Iced Espresso Classics - Caramel Macchiato
14                      Starbucks® Caramel Iced Coffee
15                       Starbucks® Iced Coffee + Milk
16           Starbucks® Low Calorie Iced Coffee + Milk
17                      Starbucks® Vanilla Iced Coffee
18                                    Shaken Sweet Tea
19                   Tazo® Bottled Berry Blossom White
20                           Tazo® Bottled Black Mango
21                      Tazo® Bottled Black with Lemon
22                          Tazo® Bottled Brambleberry
23                           Tazo® Bottled Giant Peach
24                          Tazo® Bottled Iced Passion
25                          Tazo® Bottled Lemon Ginger
26                Tazo® Bottled Organic Black Lemonade
27                Tazo® Bottled Organic Iced Black Tea
28                Tazo® Bottled Organic Iced Green Tea
29                      Tazo® Bottled Plum Pomegranate
..                                                 ...
83                         Classic Whole-Grain Oatmeal
84          Double-Smoked Bacon Cheddar & Egg Sandwich
85                              Ham & Cheese Croissant
86                            Hearty Blueberry Oatmeal
87   Reduced-Fat Turkey Bacon & Cage Free Egg White...
88            Sausage Cheddar & Egg Breakfast Sandwich
89                   Seared Steak Egg & Tomatillo Wrap
90     Slow-Roasted Ham Swiss & Egg Breakfast Sandwich
91                Sous Vide Egg Bites: Bacon & Gruyere
92         Sous Vide Egg Bites: Egg White & Red Pepper
93   Spicy Chorizo  Monterey Jack & Egg Breakfast S...
94   Spinach Feta & Cage Free Egg White Breakfast Wrap
95                      Ancho Chipotle Chicken Panini
96   Chicken & Quinoa Protein Bowl with Black Beans...
97        Chicken Artichoke on Ancient Grain Flatbread
98                          Chicken BLT Salad Sandwich
99                                  Egg Salad Sandwich
100            Homestyle Chicken & Double-Smoked Bacon
101                   Italian-Style Ham & Spicy Salami
102   Lentils & Vegetable Protein Bowl with Brown Rice
103                 Roasted Tomato & Mozzarella Panini
104                          Turkey & Havarti Sandwich
105                                Turkey Pesto Panini
106                                  Berry Trio Yogurt
107   Fresh Blueberries and Honey Greek Yogurt Parfait
108                 Justin's Chocolate Hazelnut Butter
109                     Justin's Classic Almond Butter
110                               Lemon Chiffon Yogurt
111                           Organic Avocado (Spread)
112                               Seasonal Fruit Blend

[290 rows x 1 columns]

In [ ]:
food.shape

(113, 6)

In [ ]:
food.columns=['Item','Calories','Fat','Carb','Fiber','Protein']

In [ ]:
food.head(4)

               Item  Calories   Fat  Carb  Fiber  Protein
0      Chonga Bagel       300   5.0    50      3       12
1      8-Grain Roll       380   6.0    70      7       10
2  Almond Croissant       410  22.0    45      3       10
3     Apple Fritter       460  23.0    56      2        7

In [ ]:
drink.columns=['Item','Calories','Fat','Carb','Fiber','Protein','Na']

In [ ]:
drink.head(4)

,Item,Calories,Fat,Carb,Fiber,Protein,Na
0,Cool Lime Starbucks Refreshers™ Beverage,45,0,11,0,0,10
1,Ombré Pink Drink,-,-,-,-,-,-
2,Pink Drink,-,-,-,-,-,-
3,Strawberry Acai Starbucks Refreshers™ Beverage,80,0,18,1,0,10

In [ ]:
pd.concat([drink, food], join="inner") #concatenates all common columns

,Item,Calories,Fat,Carb,Fiber,Protein
0,Cool Lime Starbucks Refreshers™ Beverage,45,0,11,0,0
1,Ombré Pink Drink,-,-,-,-,-
2,Pink Drink,-,-,-,-,-
3,Strawberry Acai Starbucks Refreshers™ Beverage,80,0,18,1,0
4,Very Berry Hibiscus Starbucks Refreshers™ Beve...,60,0,14,1,0
5,Violet Drink,-,-,-,-,-
6,Evolution Fresh™ Cold-Pressed Apple Berry Juice,-,-,-,-,-
7,Evolution Fresh™ Defense Up,-,-,-,-,-
8,Evolution Fresh™ Organic Ginger Limeade,110,0,28,0,0
9,Iced Coffee,0,0,0,0,0
10,Iced Coffee with Milk,-,-,-,-,-
11,Iced Espresso Classics - Vanilla Latte,130,2.5,21,0,5
12,Iced Espresso Classics - Caffe Mocha,140,2.5,23,0,5
13,Iced Espresso Classics - Caramel Macchiato,130,2.5,21,0,5
14,Starbucks® Caramel Iced Coffee,-,-,-,-,-
15,Starbucks® Iced Coffee + Milk,-,-,-,-,-
16,Starbucks® Low Calorie Iced Coffee + Milk,-,-,-,-,-
17,Starbucks® Vanilla Iced Coffee,-,-,-,-,-
18,Shaken Sweet Tea,80,0,19,0,0
19,Tazo® Bottled Berry Blossom White,60,0,15,0,0
20,Tazo® Bottled Black Mango,150,0,38,0,0
21,Tazo® Bottled Black with Lemon,140,0,35,0,0
22,Tazo® Bottled Brambleberry,140,0,35,0,0
23,Tazo® Bottled Giant Peach,150,0,37,0,0
24,Tazo® Bottled Iced Passion,70,0,17,0,0
25,Tazo® Bottled Lemon Ginger,120,0,31,0,0
26,Tazo® Bottled Organic Black Lemonade,140,0,35,0,0
27,Tazo® Bottled Organic Iced Black Tea,60,0,15,0,0
28,Tazo® Bottled Organic Iced Green Tea,120,0,31,0,0
29,Tazo® Bottled Plum Pomegranate,140,0,35,0,0
...,...,...,...,...,...,...
83,Classic Whole-Grain Oatmeal,160,2.5,28,4,5
84,Double-Smoked Bacon Cheddar & Egg Sandwich,490,27,40,1,21
85,Ham & Cheese Croissant,320,17,28,1,14
86,Hearty Blueberry Oatmeal,220,2.5,43,5,5
87,Reduced-Fat Turkey Bacon & Cage Free Egg White...,230,6,28,2,16
88,Sausage Cheddar & Egg Breakfast Sandwich,500,28,41,1,15
89,Seared Steak Egg & Tomatillo Wrap,410,18,43,2,21
90,Slow-Roasted Ham Swiss & Egg Breakfast Sandwich,450,23,42,1,24
91,Sous Vide Egg Bites: Bacon & Gruyere,310,22,9,0,19
92,Sous Vide Egg Bites: Egg White & Red Pepper,170,7,13,1,13
93,Spicy Chorizo Monterey Jack & Egg Breakfast S...,500,30,35,3,26
94,Spinach Feta & Cage Free Egg White Breakfast Wrap,290,10,33,6,19
95,Ancho Chipotle Chicken Panini,500,19,57,4,26
96,Chicken & Quinoa Protein Bowl with Black Beans...,420,17,42,9,27
97,Chicken Artichoke on Ancient Grain Flatbread,510,27,37,5,24
98,Chicken BLT Salad Sandwich,470,25,35,3,21
99,Egg Salad Sandwich,480,27,42,7,16
100,Homestyle Chicken & Double-Smoked Bacon,480,17,57,3,23
101,Italian-Style Ham & Spicy Salami,480,20,49,3,22
102,Lentils & Vegetable Protein Bowl with Brown Rice,650,29,80,21,23
103,Roasted Tomato & Mozzarella Panini,420,18,47,3,11
104,Turkey & Havarti Sandwich,460,21,31,2,29
105,Turkey Pesto Panini,560,23,55,3,34
106,Berry Trio Yogurt,240,2.5,39,3,14
107,Fresh Blueberries and Honey Greek Yogurt Parfait,240,2.5,42,2,14
108,Justin's Chocolate Hazelnut Butter,180,14,12,3,4
109,Justin's Classic Almond Butter,190,18,6,3,7
110,Lemon Chiffon Yogurt,340,13,38,0,18
111,Organic Avocado (Spread),90,8,5,4,1
112,Seasonal Fruit Blend,90,0,24,4,1

In [ ]:
pd.concat([drink, food]) #concatenates all columns. The values of Non common columns will contain

,Calories,Carb,Fat,Fiber,Item,Na,Protein
0,45,11,0,0,Cool Lime Starbucks Refreshers™ Beverage,10,0
1,-,-,-,-,Ombré Pink Drink,-,-
2,-,-,-,-,Pink Drink,-,-
3,80,18,0,1,Strawberry Acai Starbucks Refreshers™ Beverage,10,0
4,60,14,0,1,Very Berry Hibiscus Starbucks Refreshers™ Beve...,10,0
5,-,-,-,-,Violet Drink,-,-
6,-,-,-,-,Evolution Fresh™ Cold-Pressed Apple Berry Juice,-,-
7,-,-,-,-,Evolution Fresh™ Defense Up,-,-
8,110,28,0,0,Evolution Fresh™ Organic Ginger Limeade,5,0
9,0,0,0,0,Iced Coffee,0,0
10,-,-,-,-,Iced Coffee with Milk,-,-
11,130,21,2.5,0,Iced Espresso Classics - Vanilla Latte,65,5
12,140,23,2.5,0,Iced Espresso Classics - Caffe Mocha,90,5
13,130,21,2.5,0,Iced Espresso Classics - Caramel Macchiato,65,5
14,-,-,-,-,Starbucks® Caramel Iced Coffee,-,-
15,-,-,-,-,Starbucks® Iced Coffee + Milk,-,-
16,-,-,-,-,Starbucks® Low Calorie Iced Coffee + Milk,-,-
17,-,-,-,-,Starbucks® Vanilla Iced Coffee,-,-
18,80,19,0,0,Shaken Sweet Tea,10,0
19,60,15,0,0,Tazo® Bottled Berry Blossom White,10,0
20,150,38,0,0,Tazo® Bottled Black Mango,15,0
21,140,35,0,0,Tazo® Bottled Black with Lemon,10,0
22,140,35,0,0,Tazo® Bottled Brambleberry,15,0
23,150,37,0,0,Tazo® Bottled Giant Peach,15,0
24,70,17,0,0,Tazo® Bottled Iced Passion,10,0
25,120,31,0,0,Tazo® Bottled Lemon Ginger,10,0
26,140,35,0,0,Tazo® Bottled Organic Black Lemonade,10,0
27,60,15,0,0,Tazo® Bottled Organic Iced Black Tea,10,0
28,120,31,0,0,Tazo® Bottled Organic Iced Green Tea,10,0
29,140,35,0,0,Tazo® Bottled Plum Pomegranate,10,0
...,...,...,...,...,...,...,...
83,160,28,2.5,4,Classic Whole-Grain Oatmeal,NaN,5
84,490,40,27,1,Double-Smoked Bacon Cheddar & Egg Sandwich,NaN,21
85,320,28,17,1,Ham & Cheese Croissant,NaN,14
86,220,43,2.5,5,Hearty Blueberry Oatmeal,NaN,5
87,230,28,6,2,Reduced-Fat Turkey Bacon & Cage Free Egg White...,NaN,16
88,500,41,28,1,Sausage Cheddar & Egg Breakfast Sandwich,NaN,15
89,410,43,18,2,Seared Steak Egg & Tomatillo Wrap,NaN,21
90,450,42,23,1,Slow-Roasted Ham Swiss & Egg Breakfast Sandwich,NaN,24
91,310,9,22,0,Sous Vide Egg Bites: Bacon & Gruyere,NaN,19
92,170,13,7,1,Sous Vide Egg Bites: Egg White & Red Pepper,NaN,13
93,500,35,30,3,Spicy Chorizo Monterey Jack & Egg Breakfast S...,NaN,26
94,290,33,10,6,Spinach Feta & Cage Free Egg White Breakfast Wrap,NaN,19
95,500,57,19,4,Ancho Chipotle Chicken Panini,NaN,26
96,420,42,17,9,Chicken & Quinoa Protein Bowl with Black Beans...,NaN,27
97,510,37,27,5,Chicken Artichoke on Ancient Grain Flatbread,NaN,24
98,470,35,25,3,Chicken BLT Salad Sandwich,NaN,21
99,480,42,27,7,Egg Salad Sandwich,NaN,16
100,480,57,17,3,Homestyle Chicken & Double-Smoked Bacon,NaN,23
101,480,49,20,3,Italian-Style Ham & Spicy Salami,NaN,22
102,650,80,29,21,Lentils & Vegetable Protein Bowl with Brown Rice,NaN,23
103,420,47,18,3,Roasted Tomato & Mozzarella Panini,NaN,11
104,460,31,21,2,Turkey & Havarti Sandwich,NaN,29
105,560,55,23,3,Turkey Pesto Panini,NaN,34
106,240,39,2.5,3,Berry Trio Yogurt,NaN,14
107,240,42,2.5,2,Fresh Blueberries and Honey Greek Yogurt Parfait,NaN,14
108,180,12,14,3,Justin's Chocolate Hazelnut Butter,NaN,4
109,190,6,18,3,Justin's Classic Almond Butter,NaN,7
110,340,38,13,0,Lemon Chiffon Yogurt,NaN,18
111,90,5,8,4,Organic Avocado (Spread),NaN,1
112,90,24,0,4,Seasonal Fruit Blend,NaN,1

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
gfp=pd.read_csv("GlobalFirePower.csv")

In [ ]:
gfp.head(4)

,Country,ISO3,Rank,Total Population,Manpower Available,Fit-for-Service,Reaching Military Age,Total Military Personnel,Active Personnel,Reserve Personnel,...,Railway Coverage (km),Serivecable Airports,Defense Budget,External Debt,Foreign Exchange / Gold,Purchasing Power Parity,Square Land Area (km),Coastline (km),Shared Borders (km),Waterways (km)
0,United States,USA,1,323995528,145215000,120025000,4220000,2363675,1373650,990025,...,224792,13513,587800,17910000,117600,18560000,9826675,19924,12048,41009
1,Russia,RUS,2,142355415,70000000,47000000,1355000,3371027,798527,2572500,...,87157,1218,44600,514800,365500,3745000,17098242,37653,22408,102000
2,China,CHN,3,1373541278,750000000,619000000,19550000,3712500,2260000,1452500,...,86000,507,161700,983500,3092000,21270000,9596961,14500,22457,110000
3,India,IND,4,1266883598,616000000,489600000,22900000,4207250,1362500,2844750,...,63974,346,51000,507000,359100,8721000,3287263,7000,13888,14500

In [ ]:
gdp=pd.read_csv("countryGDP.csv")

In [ ]:
gdp.head(4)

           Country Code  Population  GDP per Capita
0      Afghanistan  AFG  32526562.0      594.323081
1          Albania  ALB   2889167.0     3945.217582
2          Algeria  ALG  39666519.0     4206.031232
3  American Samoa*  ASA     55538.0             NaN

In [ ]:
gdp.shape

(201, 4)

In [ ]:
x=pd.merge(gdp,gfp, on='Country') # #merge on column that have common entries
# default "inner" value

In [ ]:
x.head(6)

,Country,Code,Population,GDP per Capita,ISO3,Rank,Total Population,Manpower Available,Fit-for-Service,Reaching Military Age,...,Railway Coverage (km),Serivecable Airports,Defense Budget,External Debt,Foreign Exchange / Gold,Purchasing Power Parity,Square Land Area (km),Coastline (km),Shared Borders (km),Waterways (km)
0,Afghanistan,AFG,32526562.0,594.323081,AFG,69,33332025,14000000,8000000,765000,...,0,43,11500,1280,66810,64080,652230,Landlocked,5987,1200
1,Albania,ALB,2889167.0,3945.217582,ALB,90,3038594,1515000,1300000,62000,...,339,4,110,7797,3213,34210,28748,362,691,41
2,Algeria,ALG,39666519.0,4206.031232,ALG,25,40263711,20400000,17250000,675000,...,3973,157,10570,5934,115000,609400,2381741,998,6734,Minimum not met.
3,Angola,ANG,25021974.0,4101.472152,ANG,51,20172332,6030000,3040000,310000,...,2764,176,4150,37700,20430,187300,1246700,1600,5369,1300
4,Argentina,ARG,43416755.0,13431.878340,ARG,35,43886748,20000000,17000000,665000,...,36966,1138,4330,155100,32110,879400,2780400,4989,11968,11000
5,Armenia,ARM,3017712.0,3489.127690,ARM,93,3051250,1700000,1400000,45000,...,869,11,225,8365,1512,26560,29743,Landlocked,1570,Minimum not met.

In [ ]:
#merge only a few columns (Manpower avalaible and Railway coverage) with the GDP data frame using the Country column

In [ ]:
y = pd.merge(gdp,gfp[['Country', 'Manpower Available', 'Railway Coverage (km)']],
                 on='Country')

In [ ]:
y.head(5)

,Country,Code,Population,GDP per Capita,Manpower Available,Railway Coverage (km)
0,Afghanistan,AFG,32526562.0,594.323081,14000000,0
1,Albania,ALB,2889167.0,3945.217582,1515000,339
2,Algeria,ALG,39666519.0,4206.031232,20400000,3973
3,Angola,ANG,25021974.0,4101.472152,6030000,2764
4,Argentina,ARG,43416755.0,13431.878340,20000000,36966

### Database type merging

In [ ]:
#Keep every row in the left dataframe. Where there are missing values of the “on” variable in the right dataframe, add empty
y = pd.merge(gdp,gfp[['Country', 'Manpower Available', 'Railway Coverage (km)']],
                 on='Country',how='left')

In [ ]:
y.head(7)

,Country,Code,Population,GDP per Capita,Manpower Available,Railway Coverage (km)
0,Afghanistan,AFG,32526562.0,594.323081,14000000.0,0.0
1,Albania,ALB,2889167.0,3945.217582,1515000.0,339.0
2,Algeria,ALG,39666519.0,4206.031232,20400000.0,3973.0
3,American Samoa*,ASA,55538.0,NaN,NaN,NaN
4,Andorra,AND,70473.0,NaN,NaN,NaN
5,Angola,ANG,25021974.0,4101.472152,6030000.0,2764.0
6,Antigua and Barbuda,ANT,91818.0,13714.731962,NaN,NaN

In [ ]:
#why 126?

In [ ]:
gfp['Country'].isin(gdp['Country']).value_counts() #126 values of gdp appear in gfp too

True     126
False      7
Name: Country, dtype: int64

In [ ]:
y = pd.merge(gdp,gfp[['Country', 'Manpower Available', 'Railway Coverage (km)']],
                 on='Country',how='right')

# Keep every row in the right dataframe. Where there are missing values of the “on” variable in the left column, add empty

In [ ]:
y.tail(7)

,Country,Code,Population,GDP per Capita,Manpower Available,Railway Coverage (km)
126,South Korea,NaN,NaN,NaN,25610000,3381
127,North Korea,NaN,NaN,NaN,13000000,5242
128,Myanmar,NaN,NaN,NaN,30000000,5031
129,Democratic Republic of the Congo,NaN,NaN,NaN,16000000,4007
130,South Sudan,NaN,NaN,NaN,6700000,236
131,Ivory Coast,NaN,NaN,NaN,10300000,660
132,Republic of the Congo,NaN,NaN,NaN,1900000,886

In [ ]:
y = pd.merge(gdp,gfp[['Country', 'Manpower Available', 'Railway Coverage (km)']],
                 on='Country',how='outer',indicator=True)
#A full outer join returns all the rows from the left dataframe, 
#all the rows from the right dataframe, and matches up rows where possible, with NaNs elsewhere
#indicator will tell us how the joining was done

In [ ]:
y.shape

(208, 7)

In [ ]:
y.head(10)

,Country,Code,Population,GDP per Capita,Manpower Available,Railway Coverage (km),_merge
0,Afghanistan,AFG,32526562.0,594.323081,14000000.0,0.0,both
1,Albania,ALB,2889167.0,3945.217582,1515000.0,339.0,both
2,Algeria,ALG,39666519.0,4206.031232,20400000.0,3973.0,both
3,American Samoa*,ASA,55538.0,NaN,NaN,NaN,left_only
4,Andorra,AND,70473.0,NaN,NaN,NaN,left_only
5,Angola,ANG,25021974.0,4101.472152,6030000.0,2764.0,both
6,Antigua and Barbuda,ANT,91818.0,13714.731962,NaN,NaN,left_only
7,Argentina,ARG,43416755.0,13431.878340,20000000.0,36966.0,both
8,Armenia,ARM,3017712.0,3489.127690,1700000.0,869.0,both
9,Aruba*,ARU,103889.0,NaN,NaN,NaN,left_only